# 补充设计访谈状态代码段的职责说明。
"""维护 AGENTS.md 设计访谈流程的持久化状态和状态机跳转。"""

# 导入 设计访谈状态 所需的依赖模块。
from __future__ import annotations

# 分类脚本可从任意任务目录直接执行，这里补齐兄弟任务模块路径。
import sys
from pathlib import Path

_scripts_python_root = Path(__file__).resolve().parents[1]
for _task_dir in _scripts_python_root.iterdir():
    if _task_dir.is_dir():
        _task_path = str(_task_dir)
        if _task_path not in sys.path:
            sys.path.insert(0, _task_path)

# 导入 设计访谈状态 所需的依赖模块。
import json
from pathlib import Path
from typing import Any

# 导入 设计访谈状态 所需的依赖模块。
from agents_common import emit_json
from design_profile_builder import (
    attach_alignment,
    build_profile,
    infer_kind,
    review_summary,
    takeover_required,
)

# 分隔当前密集代码块，保留原有执行顺序。
from design_questions import (
    ALIGNMENT_KEY,
    COMMON_GROUPS,
    COMMON_QUESTIONS,
    DESIGN_REVIEW_KEY,
    EXTRA_REQUIREMENTS_KEY,

    # 再次分隔当前长代码块，降低连续语句密度。
    GROUP_CONFIRMATION_KEY,
    OPTIONAL_EMPTY_KEYS,
    REMOTE_CONFIGURATION_MODE_KEY,
    REMOTE_DIRECTORY_POLICY_KEYS,
    REMOTE_INSTALL_CONFIRM_KEY,
    REMOTE_SERVER_TASK_ROUTES_KEY,

    # 分隔导入清单的后续成员，避免超长连续导入块。
    REMOTE_SSH_GIT_URL,
    REMOTE_SSH_INSTALL_SPECS,
    REMOTE_SSH_SKILL_NAME,
    REMOTE_VALIDATION_STATUS_KEY,
    REVIEW_REWORK_CONFIRMATION_KEY,

    # 分隔导入清单末段，保证分组阅读边界清楚。
    STATE_PATH,
    TAKEOVER_COMMON_GROUPS,
    TERMINAL_STATUSES,
    USE_REMOTE_SERVER_KEY,
    empty,

    # 分隔最后一组导入成员，避免阅读时连续清单过长。
    groups_for,
    now_iso,
    question_ids_to_keys,
    question_rows,
    questions_for,

    # 分隔状态机导入清单尾段，避免单块导入过长。
    takeover_groups_for,
    with_options,
)
from design_remote_gate import (
    normalize_remote_server_registry,

    # 分隔远程门禁导入清单，保持状态机依赖分组清楚。
    normalize_remote_task_list,
    normalize_remote_task_routes,
    remote_choices,
    remote_configure_command_hint,
    remote_dependency_summary,
    remote_directory_policy_required,
    remote_discover,

    # 分隔远程配置导入清单尾段，降低状态机依赖密度。
    remote_gate_payload,
    remote_install_command_hint,
    resolve_remote_server_for_task,
    server_registry_map,
    set_remote_gate_payload,
    use_remote_server_enabled,
    validate_route_server_ids,

    # 分隔远程解析导入清单尾段，保持依赖阅读边界。
)
from design_takeover import autogenerated_takeover_answers, complete_takeover
from design_review_gate import (
    answers_without_design_review,
    design_review_request,
    design_review_requires_rework,
    normalize_extra_requirements,

    # 分隔状态写入导入清单尾段，结束长依赖列表。
    validate_design_review,
)
from agents_decisions import decision_request


# 定义 normalize_intent 的设计访谈状态处理入口。
def normalize_intent(value: Any) -> str:
    """把外部输入的执行意图收敛到状态机支持的两种模式。

    # 补充设计访谈状态代码段的职责说明。
    参数:
        value: CLI、JSON 状态或调用方传入的意图值。

    # 补充设计访谈状态代码段的职责说明。
    返回:
        ``read_only`` 或 ``write``；未知值按写入流程处理，保持历史默认行为。
    """

    # 先做字符串归一化，避免 None、空白和大小写差异污染状态文件。
    intent = str(value or "write").strip().lower()  # 访谈流程意图

    # 只读流程是唯一的特殊分支，其余输入都回落到写入流程。
    return "read_only" if intent == "read_only" else "write"


# 定义 review_policy_for_state 的设计访谈状态处理入口。
def review_policy_for_state(state: dict[str, Any], status: str | None = None) -> str:
    """根据当前状态判断是否需要子代理复核。

    # 补充设计访谈状态代码段的职责说明。
    参数:
        state: 设计访谈状态字典。
        status: 调用方临时指定的状态；为空时读取状态文件中的 ``status``。

    # 补充设计访谈状态代码段的职责说明。
    返回:
        复核策略标识，供交互 payload 和写入阶段判断审核边界。
    
        数组契约:
            shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
            dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
            unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 使用显式覆盖状态支持预览分支，不提前修改持久化状态。
    resolved_status = status or str(state.get("status", "collecting_group"))  # 当前状态名

    # 已完成的只读流程不能再要求写入式复核。
    if resolved_status == "completed_read_only":

        # 返回 review_policy_for_state 的访谈状态载荷。
        return "read_only_no_subagent_review"

    # 进入设计复核后的写入流程必须保留子代理复核边界。
    if resolved_status in {"awaiting_design_review", "awaiting_review_rework", "completed"}:

        # 返回 review_policy_for_state 的访谈状态载荷。
        return "subagent_review_required"

    # 只读意图在未进入写入复核前始终走轻量确认策略。
    if normalize_intent(state.get("intent")) == "read_only":

        # 返回 review_policy_for_state 的访谈状态载荷。
        return "read_only_no_subagent_review"

    # 访谈中的写入流程尚未具备最终复核对象。
    return "design_interview_in_progress"


# 定义 state_path 的设计访谈状态处理入口。
def state_path(project: Path) -> Path:
    """返回设计访谈状态文件在项目内的固定位置。"""

    # 状态文件路径由共享常量控制，避免 CLI 和恢复流程写入不同位置。
    return project / STATE_PATH


# 定义 read_state 的设计访谈状态处理入口。
def read_state(project: Path) -> dict[str, Any] | None:
    """读取项目中的设计访谈状态。

    # 补充设计访谈状态代码段的职责说明。
    参数:
        project: 工作区根目录。

    # 补充设计访谈状态代码段的职责说明。
    返回:
        合法的状态字典；文件缺失、JSON 损坏或根类型不正确时返回 ``None``。
    """

    # 统一定位状态文件，保证读取路径与写入路径完全一致。
    path_state = state_path(project)  # 设计访谈状态文件

    # 没有状态文件表示当前没有可恢复访谈。
    if not path_state.exists():

        # 返回 read_state 的访谈状态载荷。
        return None

    # 状态读取失败时保持恢复流程可继续启动新访谈。
    try:

        # 保存 state data 映射，维持 read_state 的字段关系。
        dict_state_data = json.loads(path_state.read_text(encoding="utf-8"))  # 反序列化后的状态内容
    except Exception:

        # 返回 read_state 的访谈状态载荷。
        return None

    # 仅接受对象根节点，防止数组或标量 JSON 被误当成状态。
    return dict_state_data if isinstance(dict_state_data, dict) else None


# 定义 write_state 的设计访谈状态处理入口。
def write_state(project: Path, state: dict[str, Any]) -> Path:
    """把访谈状态写回项目，并刷新更新时间。

    # 补充设计访谈状态代码段的职责说明。
    参数:
        project: 工作区根目录。
        state: 将被持久化的状态字典；调用方持有的同一对象会同步获得 ``updated_at``。

    # 补充设计访谈状态代码段的职责说明。
    返回:
        实际写入的状态文件路径。
    
        数组契约:
            shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
            dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
            unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 状态目录可能在首次访谈时尚未创建。
    path_state = state_path(project)  # 设计访谈状态文件

    # 创建父目录只影响治理状态目录，不改变项目源码结构。
    path_state.parent.mkdir(exist_ok=True)

    # 每次持久化都刷新时间戳，用于恢复流程识别最新进度。
    state["updated_at"] = now_iso()  # 访谈状态值

    # 排序写入让状态 diff 稳定，便于 handoff 和恢复排查。
    path_state.write_text(json.dumps(state, indent=2, sort_keys=True), encoding="utf-8")

    # 返回路径方便 CLI 输出或测试断言。
    return path_state


# 定义 is_active_state 的设计访谈状态处理入口。
def is_active_state(state: dict[str, Any] | None) -> bool:
    """判断状态是否仍处于可继续的访谈流程。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 空状态和终态都不应阻塞新的访谈或只读检查。
    return bool(state) and str(state.get("status", "")) not in TERMINAL_STATUSES


# 定义 initial_state 的设计访谈状态处理入口。
def initial_state(project: Path, intent: str = "write") -> dict[str, Any]:
    """构造普通交互式设计访谈的初始状态。"""

    # 初始状态字段保持稳定 JSON 结构，历史恢复和测试依赖这些 key。
    return {
        "schema_version": 1,  # 状态文件结构版本
        "mode": "interactive",  # 普通访谈模式
        "intent": normalize_intent(intent),  # 归一化后的执行意图
        "status": "collecting_group",  # 首个问题组收集阶段
        "project": str(project),  # 当前工作区路径快照
        "inferred_kind": infer_kind(project),  # 从项目事实推断出的类型
        "kind": None,  # 用户最终确认的项目类型
        "groups": COMMON_GROUPS,  # 普通访谈问题组
        "current_group_index": 0,  # 当前问题组索引
        "answers": {},  # 已收集回答
        "confirmed_group_indices": [],  # 已确认的问题组索引
        "started_at": now_iso(),  # 访谈开始时间
        "updated_at": now_iso(),  # 最近持久化时间
    }


# 定义 initial_takeover_state 的设计访谈状态处理入口。
def initial_takeover_state(project: Path, intent: str = "write") -> dict[str, Any]:
    """构造接管异常工作区时的访谈初始状态。

    # 补充设计访谈状态代码段的职责说明。
    参数:
        project: 工作区根目录。
        intent: 写入或只读意图。

    # 补充设计访谈状态代码段的职责说明。
    返回:
        包含接管触发证据快照的状态字典。

    # 补充设计访谈状态代码段的职责说明。
    异常:
        ValueError: 当前工作区不满足接管模式的前置条件。
    """

    # 接管模式只允许用于已有内容且根 AGENTS 异常的工作区。
    bool_required, dict_facts = takeover_required(project)  # 接管前置判断和证据

    # 非接管场景必须由普通访谈入口处理，避免错误写入 takeover 证据。
    if not bool_required:

        # 抛出 initial_takeover_state 已确认的阻断原因。
        raise ValueError("takeover mode requires a landed workspace with abnormal root AGENTS.md state")

    # 证据快照写入状态文件，确保后续提示不依赖临时扫描结果。
    return {
        "schema_version": 1,  # 状态文件结构版本
        "mode": "takeover",  # 接管访谈模式
        "intent": normalize_intent(intent),  # 归一化后的执行意图
        "status": "collecting_group",  # 首个接管问题组收集阶段
        "project": str(project),  # 当前工作区路径快照
        "inferred_kind": infer_kind(project),  # 从项目事实推断出的类型
        "kind": None,  # 用户最终确认的项目类型
        "groups": TAKEOVER_COMMON_GROUPS,  # 接管模式问题组
        "current_group_index": 0,  # 当前问题组索引
        "answers": {},  # 已收集回答
        "confirmed_group_indices": [],  # 已确认的问题组索引
        "started_at": now_iso(),  # 访谈开始时间
        "updated_at": now_iso(),  # 最近持久化时间
        "takeover_trigger_reasons": list(dict_facts.get("root_agents_md_trigger_reasons", [])),  # 根 AGENTS 异常原因
        "facts_snapshot": {
            "root_agents_md_exists": dict_facts.get("root_agents_md_exists", False),
            "root_agents_md_trigger_reasons": dict_facts.get("root_agents_md_trigger_reasons", []),
            "structure_fix_reasons": dict_facts.get("structure_fix_reasons", []),
            "session_history_bootstrap_required": dict_facts.get("session_history_bootstrap_required", False),
        },
    }


# 定义 move_to_extra_requirements 的设计访谈状态处理入口。
def move_to_extra_requirements(project: Path, state: dict[str, Any]) -> dict[str, Any]:
    """把访谈推进到额外需求收集阶段并返回交互 payload。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 额外需求阶段需要清除旧复核回答，避免用户回退后沿用过期审核结论。
    state["status"] = "awaiting_extra_requirements"  # 访谈状态值

    # 复核回答只对最终对齐后的内容有效。
    state.setdefault("answers", {}).pop(DESIGN_REVIEW_KEY, None)

    # 推进状态后立即持久化，保证中断恢复能停在正确阶段。
    write_state(project, state)

    # 返回下一步交互描述给 CLI 或调用方。
    return interactive_payload(project, state)


# 定义 advance_after_remote_gate 的设计访谈状态处理入口。
def advance_after_remote_gate(project: Path, state: dict[str, Any]) -> dict[str, Any]:
    """远程门禁完成后推进访谈到下一个问题组或收尾阶段。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 当前问题组索引用于判断是否已经完成全部访谈组。
    int_index = int(state.get("current_group_index", 0))  # 当前问题组索引

    # 接管模式在最后一组后交给接管收尾逻辑生成下一步状态。
    if str(state.get("mode", "interactive")) == "takeover" and int_index + 1 >= len(state.get("groups", [])):

        # 返回 advance_after_remote_gate 的访谈状态载荷。
        return complete_takeover(project, state, move_to_extra_requirements)

    # 仍有后续问题组时，继续进入普通收集阶段。
    if int_index + 1 < len(state.get("groups", [])):

        # 整理 advance_after_remote_gate 需要的 中间载荷 访谈状态。
        state["current_group_index"] = int_index + 1  # 访谈状态值

        # 整理 advance_after_remote_gate 需要的 中间载荷 访谈状态。
        state["status"] = "collecting_group"  # 访谈状态值
    else:

        # 返回 advance_after_remote_gate 的访谈状态载荷。
        return move_to_extra_requirements(project, state)

    # 持久化推进后的索引，避免远程门禁重复触发。
    write_state(project, state)

    # 返回下一组问题的交互 payload。
    return interactive_payload(project, state)


# 定义 refresh_remote_gate 的设计访谈状态处理入口。
def refresh_remote_gate(project: Path, state: dict[str, Any]) -> dict[str, Any] | None:
    """刷新远程服务器门禁状态，并在需要用户操作时返回交互 payload。

    # 补充设计访谈状态代码段的职责说明。
    返回 ``None`` 表示当前访谈未启用远程服务器治理，可继续普通问题组流程。
    
        数组契约:
            shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
            dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
            unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 远程门禁只在用户已启用远程服务器治理时生效。
    dict_answers = state.get("answers", {})  # 已收集回答

    # 非字典回答视为状态损坏，保持普通流程不触发远程依赖。
    if not isinstance(dict_answers, dict) or not use_remote_server_enabled(dict_answers):

        # 返回 refresh_remote_gate 的访谈状态载荷。
        return None

    # 门禁 payload 保留发现、选择和用户确认结果，避免重复询问。
    dict_gate = remote_gate_payload(state)  # 远程门禁状态

    # 依赖摘要判断 erie-remote-ssh 是否可用于后续服务器发现。
    dict_dependency = remote_dependency_summary()  # 远程技能依赖状态

    # 先写入依赖状态，方便缺依赖分支向用户展示安装信息。
    dict_gate.update(
        {
            "enabled": True,
            "dependency_required": True,
            "dependency_status": "installed" if dict_dependency["installed"] else "missing",
            "dependency_url": dict_dependency["url"],
            "install_specs": dict_dependency["install_specs"],
            "skill_dir": dict_dependency["skill_dir"],
        }
    )

    # 状态文件中的远程门禁字段是后续恢复远程流程的唯一依据。
    set_remote_gate_payload(state, dict_gate)

    # 依赖缺失时暂停问题组推进，等待用户安装或确认跳过。
    if not dict_dependency["installed"]:

        # 整理 refresh_remote_gate 需要的 中间载荷 访谈状态。
        state["status"] = (  # 访谈状态值
            "awaiting_remote_install_completion"  # 访谈状态值
            if dict_gate.get("install_confirmed")  # 访谈状态值
            else "awaiting_remote_install_confirmation"  # 访谈状态值
        )

        # 调用 write_state 处理 refresh_remote_gate。
        write_state(project, state)

        # 返回 refresh_remote_gate 的访谈状态载荷。
        return interactive_payload(project, state)

    # 已安装依赖后读取可用 SSH 配置状态。
    path_skill_dir = Path(dict_dependency["skill_dir"])  # erie-remote-ssh 依赖所在目录

    # 服务器发现结果决定是否进入配置补全或路由映射阶段。
    dict_discover, list_discover_errors = remote_discover(path_skill_dir)  # 远程发现结果和错误

    # 记录发现结果，恢复流程可直接展示相同证据。
    dict_gate["discover"] = dict_discover  # 访谈状态值

    # 更新门禁字段后再处理错误，保证错误页面也带有最新发现信息。
    set_remote_gate_payload(state, dict_gate)

    # 发现命令失败时保留当前阶段并把错误返回给调用方。
    if list_discover_errors:

        # 调用 write_state 处理 refresh_remote_gate。
        write_state(project, state)

        # 返回 refresh_remote_gate 的访谈状态载荷。
        return interactive_payload(project, state, errors=list_discover_errors)

    # 未配置或没有启用 SSH 时，要求用户先完成远程配置。
    if dict_discover.get("status") in {"not_configured", "no_enabled_ssh"}:

        # 整理 refresh_remote_gate 需要的 中间载荷 访谈状态。
        state["status"] = (  # 访谈状态值
            "awaiting_remote_configuration_completion"  # 访谈状态值
            if dict_gate.get("configuration_mode") in {"guided", "manual"}  # 访谈状态值
            else "awaiting_remote_configuration_confirmation"  # 访谈状态值
        )

        # 调用 write_state 处理 refresh_remote_gate。
        write_state(project, state)

        # 返回 refresh_remote_gate 的访谈状态载荷。
        return interactive_payload(project, state)

    # 配置可用后读取可选服务器列表，供用户映射任务路由。
    dict_choices, list_choice_errors = remote_choices(path_skill_dir)  # 远程服务器候选

    # 候选列表写入状态，避免下一次请求重复执行发现命令。
    dict_gate["choices"] = dict_choices  # 访谈状态值

    # 持久化选择候选，后续 payload 可直接渲染服务器选项。
    set_remote_gate_payload(state, dict_gate)

    # 候选读取失败时将错误返回给用户处理。
    if list_choice_errors:

        # 调用 write_state 处理 refresh_remote_gate。
        write_state(project, state)

        # 返回 refresh_remote_gate 的访谈状态载荷。
        return interactive_payload(project, state, errors=list_choice_errors)

    # 没有可选服务器时回到配置确认阶段，避免写入空路由。
    if dict_choices.get("status") != "available" or not dict_choices.get("servers"):

        # 整理 refresh_remote_gate 需要的 中间载荷 访谈状态。
        state["status"] = "awaiting_remote_configuration_confirmation"  # 访谈状态值

        # 调用 write_state 处理 refresh_remote_gate。
        write_state(project, state)

        # 返回 refresh_remote_gate 的访谈状态载荷。
        return interactive_payload(project, state, errors=["erie-remote-ssh choices did not return selectable servers"])

    # 依赖、配置和候选都可用后，等待用户为任务类型选择服务器路由。
    state["status"] = "awaiting_remote_server_route_mapping"  # 访谈状态值

    # 保存路由映射等待状态。
    write_state(project, state)

    # 返回包含服务器选项的交互 payload。
    return interactive_payload(project, state)


# 定义 current_group_ids 的设计访谈状态处理入口。
def current_group_ids(state: dict[str, Any]) -> list[str]:
    """返回当前问题组中的问题 ID 列表。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 状态中的 groups 可能来自旧文件，读取时需要先做类型保护。
    list_groups = state.get("groups", [])  # 状态内的问题组列表

    # 当前索引用于从问题组列表中取出正在处理的分组。
    int_index = int(state.get("current_group_index", 0))  # 当前问题组索引

    # 越界或结构异常时返回空列表，让上层 payload 给出可恢复提示。
    if not isinstance(list_groups, list) or int_index < 0 or int_index >= len(list_groups):

        # 返回 current_group_ids 的访谈状态载荷。
        return []

    # 当前分组必须是列表；否则视为没有可展示问题。
    list_group = list_groups[int_index]  # 当前问题组

    # 问题 ID 统一转成字符串，避免 JSON 数字被下游直接拼接。
    return [str(item) for item in list_group] if isinstance(list_group, list) else []


# 定义 confirmed_keys_for_state 的设计访谈状态处理入口。
def confirmed_keys_for_state(state: dict[str, Any], include_current: bool = False) -> list[str]:
    """收集已经确认的问题组对应的回答 key。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 返回顺序跟随问题组顺序，保证摘要和测试输出稳定。
    list_keys: list[str] = []  # 已确认回答 key

    # groups 可能来自旧状态文件，后续循环只接受列表分组。
    list_groups = state.get("groups", [])  # 状态内的问题组列表

    # 确认索引来自 JSON，先转成整数集合便于快速判断。
    set_confirmed_indices = set(int(item) for item in state.get("confirmed_group_indices", []))  # 已确认索引

    # 部分确认页需要把当前组作为“待确认摘要”纳入已知 key。
    if include_current and state.get("status") in {
        "awaiting_group_confirmation",
        "awaiting_extra_requirements",
        "awaiting_final_alignment",
        "awaiting_design_review",
        "completed",
        "completed_read_only",
    }:

        # 调用 add 处理 confirmed_keys_for_state。
        set_confirmed_indices.add(int(state.get("current_group_index", 0)))

    # 按原问题组顺序展开 key，避免 set 排序影响用户可读摘要。
    for int_index, list_group in enumerate(list_groups):

        # 校验 confirmed_keys_for_state 的访谈状态分支。
        if int_index in set_confirmed_indices and isinstance(list_group, list):

            # 调用 extend 处理 confirmed_keys_for_state。
            list_keys.extend(question_ids_to_keys([str(item) for item in list_group]))

    # 返回已经确认或按需包含当前组的回答 key。
    return list_keys


# 定义 remaining_groups_for_state 的设计访谈状态处理入口。
def remaining_groups_for_state(state: dict[str, Any]) -> list[list[str]]:
    """返回当前状态之后仍需要处理的问题组。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 原始问题组可能来自持久化 JSON，保留类型检查以防状态损坏。
    list_groups = state.get("groups", [])  # 状态内的问题组列表

    # 当前索引决定剩余问题组切片的起点。
    int_index = int(state.get("current_group_index", 0))  # 当前问题组索引

    # 进入收尾或完成阶段后，不再暴露剩余访谈问题。
    if state.get("status") in {
        "awaiting_extra_requirements",
        "awaiting_final_alignment",
        "awaiting_design_review",
        "awaiting_review_rework",
        "completed",
        "completed_read_only",
    }:

        # 返回 remaining_groups_for_state 的访谈状态载荷。
        return []

    # 仅在 groups 结构正常时返回字符串化问题 ID。
    return [[str(item) for item in list_group] for list_group in list_groups[int_index:]] if isinstance(list_groups, list) else []

# 定义 interactive_payload 的设计访谈状态处理入口。
def interactive_payload(
    project: Path,
    state: dict[str, Any],
    status_override: str | None = None,
    errors: list[str] | None = None,
) -> dict[str, Any]:
    """返回当前设计访谈状态对应的 CLI 交互 payload。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # payload 组装分支较多，拆到内部模块以保持状态机入口文件尺寸可控。
    from design_interview_payload import build_interactive_payload

    # 保持原公开函数签名不变，调用方仍通过本模块访问状态机入口。
    return build_interactive_payload(project, state, status_override=status_override, errors=errors)

# 定义 update_groups_after_common_confirmation 的设计访谈状态处理入口。
def update_groups_after_common_confirmation(state: dict[str, Any]) -> None:

    # 整理 update_groups_after_common_confirmation 需要的 kind 访谈状态。
    """说明 update_groups_after_common_confirmation 在 AGENTS 治理流程中的状态处理职责。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 明确该赋值在设计访谈状态流程中的业务用途。
    kind = str(state.get("answers", {}).get("development_type", "")).strip()  # 访谈状态值

    # 校验 update_groups_after_common_confirmation 的访谈状态分支。
    if kind not in {"skill", "engineering"}:

        # 抛出 update_groups_after_common_confirmation 已确认的阻断原因。
        raise ValueError("development_type must be skill or engineering after common confirmation")

    # 整理 update_groups_after_common_confirmation 需要的 中间载荷 访谈状态。
    state["kind"] = kind  # 访谈状态值

    # 校验 update_groups_after_common_confirmation 的访谈状态分支。
    if str(state.get("mode", "interactive")) == "takeover":

        # 整理 update_groups_after_common_confirmation 需要的 中间载荷 访谈状态。
        state["groups"] = takeover_groups_for(kind)  # 访谈状态值
    else:

        # 整理 update_groups_after_common_confirmation 需要的 中间载荷 访谈状态。
        state["groups"] = groups_for(kind)  # 访谈状态值

# 定义 validate_group_answers 的设计访谈状态处理入口。
def validate_group_answers(payload: dict[str, Any], expected_keys: list[str]) -> list[str]:

    # 返回 validate_group_answers 的访谈状态载荷。
    return validate_group_answers_with_optional(payload, expected_keys, expected_keys)


# 定义 validate_group_answers_with_optional 的设计访谈状态处理入口。
def validate_group_answers_with_optional(
    payload: dict[str, Any],
    expected_keys: list[str],
    required_keys: list[str],
) -> list[str]:

    # 收集 provided keys 访谈条目。
    set_provided_keys = set(payload)  # 访谈状态值

    # 整理 validate_group_answers_with_optional 需要的 expected 访谈状态。
    set_expected = set(expected_keys)  # 访谈状态值

    # 整理 validate_group_answers_with_optional 需要的 required 访谈状态。
    set_required = set(required_keys)  # 访谈状态值

    # 收集 errors 访谈条目。
    list_errors: list[str] = []  # 访谈状态值

    # 整理 validate_group_answers_with_optional 需要的 extra 访谈状态。
    extra = sorted(set_provided_keys - set_expected)  # 访谈状态值

    # 整理 validate_group_answers_with_optional 需要的 missing 访谈状态。
    missing = sorted(set_required - set_provided_keys)  # 访谈状态值

    # 校验 validate_group_answers_with_optional 的访谈状态分支。
    if extra:

        # 追加 validate_group_answers_with_optional 的访谈诊断。
        list_errors.append(f"out-of-group answers are not allowed for this step: {', '.join(extra)}")

    # 逐项检查 validate_group_answers_with_optional 访谈候选。
    for key in missing:

        # 追加 validate_group_answers_with_optional 的访谈诊断。
        list_errors.append(f"missing required answer: {key}")

    # 逐项检查 validate_group_answers_with_optional 访谈候选。
    for key in required_keys:

        # 校验 validate_group_answers_with_optional 的访谈状态分支。
        if key in OPTIONAL_EMPTY_KEYS and key in payload:

            # 分隔 validate_group_answers_with_optional 的控制流边界。
            continue

        # 校验 validate_group_answers_with_optional 的访谈状态分支。
        if key in payload and empty(payload[key]):

            # 追加 validate_group_answers_with_optional 的访谈诊断。
            list_errors.append(f"missing required answer: {key}")

    # 返回 validate_group_answers_with_optional 的访谈状态载荷。
    return list_errors

# 定义 answer_group 的设计访谈状态处理入口。
def answer_group(project: Path, state: dict[str, Any], payload: dict[str, Any]) -> dict[str, Any]:

    # 收集 group ids 访谈条目。
    """说明 answer_group 在 AGENTS 治理流程中的状态处理职责。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 明确该赋值在设计访谈状态流程中的业务用途。
    list_group_ids = current_group_ids(state)  # 访谈状态值

    # 收集 expected keys 访谈条目。
    expected_keys = question_ids_to_keys(list_group_ids)  # 访谈状态值

    # 收集 merged answers 访谈条目。
    dict_merged_answers = dict(state.get("answers", {}))  # 访谈状态值

    # 调用 update 处理 answer_group。
    dict_merged_answers.update(payload)

    # 收集 required keys 访谈条目。
    list_required_keys = list(expected_keys)  # 访谈状态值

    # 校验 answer_group 的访谈状态分支。
    if any(key in expected_keys for key in REMOTE_DIRECTORY_POLICY_KEYS) and not remote_directory_policy_required(dict_merged_answers):

        # 收集 required keys 访谈条目。
        list_required_keys = [key for key in expected_keys if key not in REMOTE_DIRECTORY_POLICY_KEYS]  # 访谈状态值

    # 收集 errors 访谈条目。
    list_errors = validate_group_answers_with_optional(payload, expected_keys, list_required_keys)  # 访谈状态值

    # 校验 answer_group 的访谈状态分支。
    if list_errors:

        # 调用 emit_json 处理 answer_group。
        emit_json(interactive_payload(project, state, errors=list_errors))

        # 抛出 answer_group 已确认的阻断原因。
        raise SystemExit(1)

    # 收集 answers 访谈条目。
    answers = state.setdefault("answers", {})  # 访谈状态值

    # 调用 update 处理 answer_group。
    answers.update(payload)

    # 校验 answer_group 的访谈状态分支。
    if any(key in expected_keys for key in REMOTE_DIRECTORY_POLICY_KEYS) and not remote_directory_policy_required(answers):

        # 调用 setdefault 处理 answer_group。
        answers.setdefault("remote_conda_environment_layout", "disabled")

        # 调用 setdefault 处理 answer_group。
        answers.setdefault("remote_run_artifact_active_layout", "disabled")

        # 调用 setdefault 处理 answer_group。
        answers.setdefault("remote_run_artifact_backup_layout", "disabled")

        # 调用 setdefault 处理 answer_group。
        answers.setdefault("remote_run_archive_trigger", "disabled")

    # 整理 answer_group 需要的 中间载荷 访谈状态。
    state["status"] = "awaiting_group_confirmation"  # 访谈状态值

    # 调用 write_state 处理 answer_group。
    write_state(project, state)

    # 返回 answer_group 的访谈状态载荷。
    return interactive_payload(project, state)

# 定义 disable_remote_gate_and_continue 的设计访谈状态处理入口。
def disable_remote_gate_and_continue(project: Path, state: dict[str, Any]) -> dict[str, Any]:

    # 整理 disable_remote_gate_and_continue 需要的 中间载荷 访谈状态。
    """说明 disable_remote_gate_and_continue 在 AGENTS 治理流程中的状态处理职责。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 明确该赋值在设计访谈状态流程中的业务用途。
    state.setdefault("answers", {})[USE_REMOTE_SERVER_KEY] = False  # 访谈状态值

    # 调用 pop 处理 disable_remote_gate_and_continue。
    state.pop("remote_server_gate", None)

    # 返回 disable_remote_gate_and_continue 的访谈状态载荷。
    return advance_after_remote_gate(project, state)

# 定义 answer_remote_install_confirmation 的设计访谈状态处理入口。
def answer_remote_install_confirmation(project: Path, state: dict[str, Any], payload: dict[str, Any]) -> dict[str, Any]:

    # 校验 answer_remote_install_confirmation 的访谈状态分支。
    """说明 answer_remote_install_confirmation 在 AGENTS 治理流程中的状态处理职责。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 说明该控制语句在设计访谈状态流程中的分支职责。
    if payload.get(USE_REMOTE_SERVER_KEY) is False:

        # 返回 answer_remote_install_confirmation 的访谈状态载荷。
        return disable_remote_gate_and_continue(project, state)

    # 校验 answer_remote_install_confirmation 的访谈状态分支。
    if REMOTE_INSTALL_CONFIRM_KEY not in payload or not isinstance(payload[REMOTE_INSTALL_CONFIRM_KEY], bool):

        # 调用 emit_json 处理 answer_remote_install_confirmation。
        emit_json(interactive_payload(project, state, errors=[f"{REMOTE_INSTALL_CONFIRM_KEY} must be provided as true or false"]))

        # 抛出 answer_remote_install_confirmation 已确认的阻断原因。
        raise SystemExit(1)

    # 校验 answer_remote_install_confirmation 的访谈状态分支。
    if payload[REMOTE_INSTALL_CONFIRM_KEY]:

        # 整理 answer_remote_install_confirmation 需要的 gate 访谈状态。
        gate = remote_gate_payload(state)  # 访谈状态值

        # 整理 answer_remote_install_confirmation 需要的 中间载荷 访谈状态。
        gate["install_confirmed"] = True  # 访谈状态值

        # 调用 set_remote_gate_payload 处理 answer_remote_install_confirmation。
        set_remote_gate_payload(state, gate)

        # 整理 answer_remote_install_confirmation 需要的 中间载荷 访谈状态。
        state["status"] = "awaiting_remote_install_completion"  # 访谈状态值

        # 调用 write_state 处理 answer_remote_install_confirmation。
        write_state(project, state)

        # 返回 answer_remote_install_confirmation 的访谈状态载荷。
        return interactive_payload(project, state)

    # remote install 被取消时向调用方返回可恢复的阻断原因。
    list_errors = [  # 远程依赖缺失时返回给交互层的阻断原因
        "remote server flow remains blocked until erie-remote-ssh is installed "  # 远程依赖缺失说明
        "or use_remote_server is changed to false"  # 关闭远程流程的替代动作
    ]

    # 将阻断原因写入交互响应，保持状态文件不被误判为完成。
    emit_json(interactive_payload(project, state, errors=list_errors))

    # 抛出 answer_remote_install_confirmation 已确认的阻断原因。
    raise SystemExit(1)

# 定义 answer_remote_configuration_confirmation 的设计访谈状态处理入口。
def answer_remote_configuration_confirmation(project: Path, state: dict[str, Any], payload: dict[str, Any]) -> dict[str, Any]:

    # 校验 answer_remote_configuration_confirmation 的访谈状态分支。
    """说明 answer_remote_configuration_confirmation 在 AGENTS 治理流程中的状态处理职责。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 说明该控制语句在设计访谈状态流程中的分支职责。
    if payload.get(USE_REMOTE_SERVER_KEY) is False:

        # 返回 answer_remote_configuration_confirmation 的访谈状态载荷。
        return disable_remote_gate_and_continue(project, state)

    # 整理 answer_remote_configuration_confirmation 需要的 mode 访谈状态。
    mode = str(payload.get(REMOTE_CONFIGURATION_MODE_KEY, "")).strip().lower()  # 访谈状态值

    # 校验 answer_remote_configuration_confirmation 的访谈状态分支。
    if mode not in {"guided", "manual", "cancel"}:

        # 调用 emit_json 处理 answer_remote_configuration_confirmation。
        emit_json(interactive_payload(project, state, errors=[f"{REMOTE_CONFIGURATION_MODE_KEY} must be guided, manual, or cancel"]))

        # 抛出 answer_remote_configuration_confirmation 已确认的阻断原因。
        raise SystemExit(1)

    # 校验 answer_remote_configuration_confirmation 的访谈状态分支。
    if mode == "cancel":

        # remote configuration 被取消时向调用方返回可恢复的阻断原因。
        list_errors = [  # 远程配置未完成时返回给交互层的阻断原因
            "remote server flow remains blocked until configuration is completed "  # 远程配置缺失说明
            "or use_remote_server is changed to false"  # 关闭远程流程的替代动作
        ]

        # 将阻断原因写入交互响应，保持状态文件不被误判为完成。
        emit_json(interactive_payload(project, state, errors=list_errors))

        # 抛出 answer_remote_configuration_confirmation 已确认的阻断原因。
        raise SystemExit(1)

    # 整理 answer_remote_configuration_confirmation 需要的 gate 访谈状态。
    gate = remote_gate_payload(state)  # 访谈状态值

    # 整理 answer_remote_configuration_confirmation 需要的 中间载荷 访谈状态。
    gate["configuration_mode"] = mode  # 访谈状态值

    # 调用 set_remote_gate_payload 处理 answer_remote_configuration_confirmation。
    set_remote_gate_payload(state, gate)

    # 整理 answer_remote_configuration_confirmation 需要的 中间载荷 访谈状态。
    state["status"] = "awaiting_remote_configuration_completion"  # 访谈状态值

    # 调用 write_state 处理 answer_remote_configuration_confirmation。
    write_state(project, state)

    # 返回 answer_remote_configuration_confirmation 的访谈状态载荷。
    return interactive_payload(project, state)

# 定义 answer_remote_server_route_mapping 的设计访谈状态处理入口。
