"""为旧工作区合成接管答案并推进设计访谈状态。"""

# future 注解推迟求值，保持旧版 Python 运行时兼容。
from __future__ import annotations

# 标准库提供项目根路径和通用映射类型。
from pathlib import Path
from typing import Any, Callable

# 命令构造器生成 owner skill 的治理验证命令。
from agents_common import script_command

# 画像构建辅助函数提供项目类型推断和分支策略合同。
from design_profile_builder import git_branch_policy, infer_kind

# 状态字段常量保持接管流程与访谈状态机一致。
from design_questions import ALIGNMENT_KEY, DESIGN_REVIEW_KEY

# 技能接管验证链必须覆盖结构、治理、文档和评估。
def _skill_validation_gates(project: Path, str_name: str) -> str:
    """构造技能接管完成后的验证命令链。

    参数：
        project: 当前工作区根目录。
        str_name: 接管目标技能名称。
    返回：
        使用分号连接且保持既有顺序的验证命令文本。
    """

    # 技能源码根用于所有 owner-repo 自举检查。
    str_skill_root = f"skills/{str_name}"  # 接管目标技能的仓库相对根目录。

    # 技能脚本前缀定位发布包内的 Python 治理入口。
    str_script_root = f"{str_skill_root}/scripts/python"  # 技能 Python 脚本目录。

    # AGENTS 验证命令同时检查仓库根规则和目标技能目录。
    str_verify_agents = script_command(  # AGENTS 治理验证命令。
        project,  # owner skill 所在项目根目录。
        "verify_agents.py",  # AGENTS 合同验证入口。
        ".",  # 当前项目验证目标。
        "--installed-skill-dir",  # 目标技能目录参数名。
        str_skill_root,  # 接管后的技能源码根。
    )

    # 文档验证确认 session、handoff 和 memory 状态一致。
    str_verify_docs = script_command(  # 文档治理验证命令。
        project,  # 文档状态所属的项目根目录。
        "manage_docs.py",  # 文档治理入口。
        "verify",  # 文档状态验证子命令。
        ".",  # 文档治理校验的当前目录。
    )

    # 技能评估命令覆盖画像与仓库事实的匹配程度。
    str_evaluate_skill = script_command(  # 技能评估命令。
        project,  # 技能画像所属的项目根目录。
        "evaluate_skill.py",  # 技能评估入口。
        str_skill_root,  # 待评估技能源码根。
        ".",  # 评估仓库事实的当前目录。
    )

    # 固定命令顺序保持历史控制画像和测试合同稳定。
    list_validation_commands = [
        f"python {str_script_root}/verify/quick_validate.py {str_skill_root}",  # 快速验证技能包结构。
        f"python {str_script_root}/verify/audit_skill.py {str_skill_root}",  # 审计技能治理合同。
        str_verify_agents,  # 验证根 AGENTS 与安装技能元数据。
        str_verify_docs,  # 验证文档治理状态。
        str_evaluate_skill,  # 运行技能画像评估。
    ]  # 接管技能的完整验证命令序列。

    # 控制画像继续使用单个文本字段承载命令链。
    return "; ".join(list_validation_commands)

# 技能画像字段描述接管后的源码、治理和发布责任。
def _skill_takeover_answers(project: Path, str_name: str) -> dict[str, Any]:
    """合成旧技能工作区的接管默认答案。

    参数：
        project: 当前工作区根目录。
        str_name: 接管目标技能名称。
    返回：
        不含用户已有答案覆盖项的技能接管默认映射。
    """

    # 技能目录前缀复用于资源计划和命令描述。
    str_primary_root = f"skills/{str_name}/"  # 接管技能的主要源码目录。

    # 验证合同通过 owner skill 自举命令生成。
    str_validation_gates = _skill_validation_gates(project, str_name)  # 技能接管验证命令链。

    # 默认字段仅补齐 takeover 允许自动推断的描述性答案。
    return {
        "development_type": "skill",  # 接管项目类型。
        "name": str_name,  # 接管目标技能名称。
        "skill_purpose": f"Take over and govern the existing `{str_name}` skill workspace.",  # 技能接管用途。
        "skill_reason": (
            "Root AGENTS.md is missing or outdated, so the workspace must be brought "
            "under strict governance immediately."
        ),  # 技能接管原因。
        "reference_materials": ["none"],  # 默认无外部参考材料。
        "audience": "existing workspace maintainers",  # 接管画像目标受众。
        "design_notes": (
            "This control profile was generated by takeover mode from repository facts "
            "and minimal user confirmation."
        ),  # 接管画像生成说明。
        "trigger_scenarios": (
            "Use when an existing skill workspace needs AGENTS.md takeover, governance "
            "repair, or version-aligned regeneration."
        ),  # 技能接管触发场景。
        "skill_design_patterns": ["Tool Wrapper", "Generator", "Reviewer", "Inversion", "Pipeline"],  # 既有技能常用设计模式。
        "resource_plan": (
            f"{str_primary_root} for skill source, tests/ for verification, "
            "dist/ for release packages, docs/ for governance, and .agents/ for control state."
        ),  # 技能源码、测试、发布和治理目录职责。
        "progressive_disclosure_policy": (
            "Keep SKILL.md concise, move detailed policy into references/, and let scripts "
            "own deterministic governance work."
        ),  # 技能渐进披露规则。
        "validation_gates": str_validation_gates,  # 接管完成后的验证命令链。
        "forward_testing_policy": (
            "Forward-test takeover and governance repair flows with fresh fixtures before "
            "claiming readiness."
        ),  # 接管流程前向测试规则。
        "development_requirements": (
            "Force-take over the existing skill workspace, normalize structure, "
            "rebuild governance docs, and restore version-aligned AGENTS control."
        ),  # 技能接管开发要求。
        "expected_outcome": (
            "The existing skill workspace is reorganized under the governed structure "
            "and can be maintained through the standard agents-md-generator workflow."
        ),  # 技能接管预期结果。
        "validation_method": "automated scripts plus user review",  # 技能接管验证方式。
        "validation_granularity": (
            "unit tests, AGENTS verification, docs governance verification, and evaluate chain"
        ),  # 技能接管验证粒度。
    }

# 工程画像字段描述接管后的项目根和治理责任。
def _engineering_takeover_answers(str_name: str) -> dict[str, Any]:
    """合成旧工程工作区的接管默认答案。

    参数：
        str_name: 接管目标工程名称。
    返回：
        不含用户已有答案覆盖项的工程接管默认映射。
    """

    # 工程目录前缀写入资源计划并供发布范围复用。
    str_primary_root = f"engineering/{str_name}/"  # 接管工程的主要项目目录。

    # 工程默认画像不启用任何专用工程规则集。
    return {
        "development_type": "engineering",  # 工程接管画像类型。
        "name": str_name,  # 接管目标工程名称。
        "project_purpose": f"Take over and govern the existing `{str_name}` engineering workspace.",  # 工程接管用途。
        "project_reason": (
            "Root AGENTS.md is missing or outdated, so the engineering workspace must be "
            "reorganized and brought under strict governance."
        ),  # 工程接管原因。
        "reusable_experience": (
            "This control profile was generated by takeover mode from repository facts "
            "and minimal user confirmation."
        ),  # 工程接管经验说明。
        "development_requirements": (
            "Force-take over the existing engineering workspace, normalize the local "
            "directory structure, and rebuild governance records without a full design interview."
        ),  # 工程接管开发要求。
        "expected_outcome": (
            "The engineering workspace is reorganized under the governed project root "
            "and all AGENTS/docs governance gates become enforceable."
        ),  # 工程接管预期结果。
        "environment": "local",  # 工程接管默认运行环境。
        "resource_plan": (
            f"{str_primary_root} for source and project files, tests/ for verification, "
            "dist/ for release artifacts, docs/ for governance, and .agents/ for control state."
        ),  # 工程源码、测试、发布和治理目录职责。
        "validation_method": "automated scripts plus user review",  # 工程接管验证方式。
        "validation_granularity": (
            "unit tests, AGENTS verification, docs governance verification, and evaluate chain"
        ),  # 工程接管验证粒度。
        "forward_testing_policy": (
            "Forward-test takeover restructuring and governance repair with fresh engineering "
            "fixtures before claiming readiness."
        ),  # 工程接管前向测试规则。
        "engineering_rule_primary": "none",  # 默认不选择主工程规则集。
        "engineering_rule_mode": "none",  # 默认不启用工程规则模式。
        "engineering_rule_scope": "on-demand",  # 工程规则默认按需加载。
        "engineering_rule_notes": "",  # 默认无工程规则补充说明。
    }

# 公共答案补齐 Git、发布、对齐和既有工作状态。
def _common_takeover_answers(
    str_name: str,
    dict_answers: dict[str, Any],
    str_kind: str,
) -> dict[str, Any]:
    """构造技能与工程接管共享的默认答案。

    参数：
        str_name: 接管目标名称。
        dict_answers: 用户已经确认的设计答案。
        str_kind: skill 或 engineering 项目类型。
    返回：
        可与类型专用默认答案合并的公共字段映射。
    """

    # 参考材料默认值随项目类型变化，但允许用户答案覆盖。
    list_default_references = ["none"] if str_kind == "skill" else []  # 类型对应的默认参考材料。

    # 公共字段保持 takeover 历史写入合同不变。
    return {
        "git_management": "yes-local-only",  # Git 仅在本地管理。
        "branch_model": "master-and-dist-release",  # 接管分支与发布模型。
        "release_contract": f"dist/{str_name}-vx.x.x plus zip",  # 版本化发布目录和压缩包合同。
        "has_existing_work": "yes",  # 接管目标已经存在落地内容。
        "takeover_mode": True,  # 标记答案来自接管流程。
        ALIGNMENT_KEY: True,  # 自动合成阶段暂存对齐状态。
        "reference_materials": dict_answers.get(
            "reference_materials",  # 用户答案中的参考材料字段。
            list_default_references,  # 项目类型对应的默认参考材料。
        ),  # 用户确认或默认参考材料。
    }

# 接管触发原因写入类型对应的长期说明字段。
def _append_takeover_reason(
    dict_synthesized: dict[str, Any],
    str_kind: str,
    list_takeover_reasons: list[str],
) -> None:
    """把接管触发事实附加到画像说明字段。

    参数：
        dict_synthesized: 已合并用户答案的接管画像。
        str_kind: skill 或 engineering 项目类型。
        list_takeover_reasons: 检测器记录的接管触发原因。
    返回：
        无业务返回值；函数原地更新画像说明字段。
    """

    # 空原因列表使用稳定的通用接管说明。
    str_reason_text = ", ".join(list_takeover_reasons) or "workspace takeover required"  # 接管触发原因文本。

    # 技能接管把触发事实追加到设计备注。
    if str_kind == "skill":

        # 保留已有备注并在末尾增加可审计原因。
        dict_synthesized["design_notes"] = (  # 带接管原因的技能设计备注。
            f"{dict_synthesized['design_notes']} Takeover reasons: {str_reason_text}."  # 技能备注追加文本。
        )

    # 工程接管把同一事实追加到可复用经验。
    else:

        # 保留工程经验正文并记录本次接管来源。
        dict_synthesized["reusable_experience"] = (  # 带接管原因的工程经验说明。
            f"{dict_synthesized['reusable_experience']} Takeover reasons: {str_reason_text}."  # 工程经验追加文本。
        )

# 公开入口合成 takeover 模式后续流程需要的完整答案。
def autogenerated_takeover_answers(project: Path, state: dict[str, Any]) -> dict[str, Any]:
    """根据项目事实和已确认答案合成接管画像。

    参数：
        project: 当前工作区根目录。
        state: 设计访谈状态映射。
    返回：
        用户答案优先且包含接管治理合同的完整答案映射。
    数组契约：
        shape/维度: 输入输出为治理映射，不处理数值数组。
        dtype/类型: 字段由 dict、list、str、bool 和 Path 等业务类型组成。
        unit/单位: 所有字段均为治理语义，无物理单位。
    """

    # 已有答案复制后再参与类型推断和最终覆盖。
    dict_answers = dict(state.get("answers", {}))  # 当前访谈已经确认的答案。

    # 状态类型、答案类型和项目事实按优先级确定接管类型。
    str_kind = str(  # 接管目标的项目类型。
        state.get("kind")  # 状态机已经确认的项目类型。
        or dict_answers.get("development_type")  # 用户答案中的项目类型。
        or infer_kind(project)  # 根据仓库事实推断的类型。
    ).strip()

    # 技能和工程采用不同的稳定回退名称。
    str_default_name = "takeover-skill" if str_kind == "skill" else "takeover-project"  # 类型对应的回退名称。

    # 用户确认名称优先于回退名称。
    str_name = str(dict_answers.get("name") or str_default_name).strip()  # 接管目标规范化名称。

    # 默认语言只在用户或访谈状态已明确给出时写回。
    str_default_language = str(dict_answers.get("default_conversation_language", "")).strip()  # 已确认默认语言。

    # 类型专用默认答案承载技能或工程的描述合同。
    if str_kind == "skill":

        # 技能接管需要额外生成 owner-repo 验证命令链。
        dict_synthesized = _skill_takeover_answers(project, str_name)  # 技能接管默认画像。

    # 非技能类型沿用历史工程接管分支。
    else:

        # 工程接管不生成技能发布专用字段。
        dict_synthesized = _engineering_takeover_answers(str_name)  # 工程接管默认画像。

    # 公共治理字段覆盖类型专用映射中的共享默认值。
    dict_synthesized.update(_common_takeover_answers(str_name, dict_answers, str_kind))

    # 用户已经确认的答案拥有最终优先级。
    dict_synthesized.update(dict_answers)

    # 默认语言不能由接管流程静默推断。
    if str_default_language:

        # 明确语言写入最终答案供后续强制校验。
        dict_synthesized["default_conversation_language"] = str_default_language  # 用户确认的默认会话语言。

    # 接管自动合成阶段保持现有对齐标志语义。
    dict_synthesized[ALIGNMENT_KEY] = True  # 接管答案当前对齐状态。

    # 分支策略副本将限制发布准备可修改路径。
    dict_branch_policy = git_branch_policy()  # 当前仓库分支治理合同。

    # 发布主目录优先采用用户确认的本地目录合同。
    str_primary_root = str(  # 发布准备允许的主要项目目录。
        dict_synthesized.get(  # 用户确认或类型默认的本地目录结构。
            "local_directory_structure",  # 本地目录合同字段名。
            f"skills/{str_name}/" if str_kind == "skill" else f"engineering/{str_name}/",  # 类型默认主目录。
        )
    ).split(",")[0].strip().rstrip("/")

    # 接管后的发布准备只能触及治理和项目必需目录。
    dict_branch_policy["release_prepare_allowed_paths"] = [
        str_primary_root,  # 项目或技能主要源码目录。
        "tests",  # 自动化测试目录。
        "docs",  # 治理文档目录。
        ".agents",  # 智能体控制状态目录。
        "AGENTS.md",  # 根级智能体规则文件。
        "dist",  # 版本发布目录。
    ]

    # 完整分支合同进入接管答案供画像构建器消费。
    dict_synthesized["git_branch_policy"] = dict_branch_policy  # 接管后的分支治理合同。

    # 检测器记录的接管原因用于后续事实审计。
    list_takeover_reasons = list(state.get("takeover_trigger_reasons", []))  # 接管触发原因列表。

    # 类型对应的说明字段追加本次触发事实。
    _append_takeover_reason(dict_synthesized, str_kind, list_takeover_reasons)

    # 返回可继续补充目录合同和用户确认的接管答案。
    return dict_synthesized

# 完成入口清理临时状态并转入附加要求确认阶段。
def complete_takeover(
    project: Path,
    state: dict[str, Any],
    move_to_extra_requirements: Callable[[Path, dict[str, Any]], dict[str, Any]],
) -> dict[str, Any]:
    """完成接管答案合成并推进访谈状态机。

    参数：
        project: 当前工作区根目录。
        state: 待更新的设计访谈状态映射。
        move_to_extra_requirements: 推进到附加要求阶段的状态转换函数。
    返回：
        状态转换函数返回的下一阶段响应映射。
    数组契约：
        shape/维度: 状态映射不包含数值数组计算，维度不适用。
        dtype/类型: 输入输出使用 Path、dict 和 Callable 业务类型。
        unit/单位: 状态字段均为治理语义，无物理单位。
    """

    # 完整接管答案先由公开合成入口生成。
    dict_final_answers = autogenerated_takeover_answers(project, state)  # 接管完成阶段的最终答案。

    # 最终对齐必须在后续用户确认步骤重新建立。
    dict_final_answers.pop(ALIGNMENT_KEY, None)

    # 旧审查证据不能应用到重新合成的接管答案。
    dict_final_answers.pop(DESIGN_REVIEW_KEY, None)

    # 清理后的答案替换状态中的临时回答集合。
    state["answers"] = dict_final_answers  # 等待附加要求确认的接管答案。

    # 旧画像预览不再对应当前接管答案。
    state.pop("profile_preview", None)

    # 状态机继续执行附加要求确认合同。
    return move_to_extra_requirements(project, state)
