from __future__ import annotations

# 分类脚本可从任意任务目录直接执行，这里补齐兄弟任务模块路径。
import sys
from pathlib import Path

_scripts_python_root = Path(__file__).resolve().parents[1]
for _task_dir in _scripts_python_root.iterdir():
    if _task_dir.is_dir():
        _task_path = str(_task_dir)
        if _task_path not in sys.path:
            sys.path.insert(0, _task_path)

# 导入 脚本治理 所需的依赖模块。
from pathlib import Path
import sys
from typing import Any

# 保留 dont write bytecode 中间值，支撑 模块入口 的当前计算步骤。
sys.dont_write_bytecode = True  # dont write bytecode 用于本步治理判断

# 导入 脚本治理 所需的依赖模块。
from agents_common import script_command
from design_profile_builder import git_branch_policy, infer_kind
from design_questions import ALIGNMENT_KEY, DESIGN_REVIEW_KEY


# 定义 autogenerated_takeover_answers 的脚本治理处理入口。
def autogenerated_takeover_answers(project: Path, state: dict[str, Any]) -> dict[str, Any]:

    # 收集 answers 条目，保持 autogenerated_takeover_answers 的处理顺序稳定。
    """说明 autogenerated_takeover_answers 在 AGENTS 治理流程中的状态处理职责。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 明确该赋值在接管流程流程中的业务用途。
    dict_answers = dict(state.get("answers", {}))  # answers 用于本步治理判断

    # 保留 kind 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
    kind = str(state.get("kind") or dict_answers.get("development_type") or infer_kind(project)).strip()  # kind 用于本步治理判断

    # 保留 name key 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
    str_name_key = "name"  # name key 用于本步治理判断

    # 检查 autogenerated_takeover_answers 的当前条件是否需要进入专门分支。
    if kind == "skill":

        # 保留 name value 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
        name_value = str(dict_answers.get(str_name_key) or dict_answers.get("name") or "takeover-skill").strip()  # name value 用于本步治理判断
    else:

        # 保留 name value 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
        name_value = str(dict_answers.get(str_name_key) or dict_answers.get("name") or "takeover-project").strip()  # name value 用于本步治理判断

    # 保留 default language 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
    default_language = str(dict_answers.get("default_conversation_language", "")).strip()  # default language 用于本步治理判断

    # 保留 local primary 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
    local_primary = f"skills/{name_value}/" if kind == "skill" else f"engineering/{name_value}/"  # local primary 用于本步治理判断

    # 检查 autogenerated_takeover_answers 的当前条件是否需要进入专门分支。
    if kind == "skill":

        # 保留 local skill root 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
        local_skill_root = local_primary.rstrip("/")  # local skill root 用于本步治理判断

        # 保留 governance verify 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
        governance_verify = script_command(project, "verify_agents.py", ".", "--installed-skill-dir", local_skill_root)  # governance verify 用于本步治理判断

        # 保留 governance docs verify 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
        governance_docs_verify = script_command(project, "manage_docs.py", "verify", ".")  # governance docs verify 用于本步治理判断

        # 保留 governance evaluate 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
        governance_evaluate = script_command(project, "evaluate_skill.py", local_skill_root, ".")  # governance evaluate 用于本步治理判断

        # 保留 synthesized 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
        # 验证命令链保持原分号分隔格式，只把拼接步骤拆开。
        str_validation_gates = "; ".join(  # 接管技能工作区发布前的校验流程串联文本
            [
                f"python {local_primary}scripts/python/verify/quick_validate.py {local_skill_root}",  # 快速校验技能结构
                f"python {local_primary}scripts/python/verify/audit_skill.py {local_skill_root}",  # 审计技能发布约束
                governance_verify,  # 校验根代理规则文件
                governance_docs_verify,  # 校验文档治理状态
                governance_evaluate,  # 运行技能评估流程
            ]
        )

        # 保留 synthesized 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
        dict_synthesized = {  # synthesized 用于本步治理判断
            "development_type": "skill",  # synthesized 用于本步治理判断
            "name": name_value,  # synthesized 用于本步治理判断
            "skill_purpose": f"Take over and govern the existing `{name_value}` skill workspace.",  # synthesized 用于本步治理判断
            "skill_reason": "Root AGENTS.md is missing or outdated, so the workspace must be brought under strict governance immediately.",  # synthesized 用于本步治理判断
            "reference_materials": ["none"],  # synthesized 用于本步治理判断
            "audience": "existing workspace maintainers",  # synthesized 用于本步治理判断
            "design_notes": "This control profile was generated by takeover mode from repository facts and minimal user confirmation.",  # synthesized 用于本步治理判断
            "trigger_scenarios": "Use when an existing skill workspace needs AGENTS.md takeover, governance repair, or version-aligned regeneration.",  # synthesized 用于本步治理判断
            "skill_design_patterns": ["Tool Wrapper", "Generator", "Reviewer", "Inversion", "Pipeline"],  # synthesized 用于本步治理判断
            "resource_plan": (  # takeover skill 目录职责说明
                f"{local_primary} for skill source, tests/ for verification, "  # skill 源码和测试目录职责
                "dist/ for release packages, docs/ for governance, and .agents/ for control state."  # release 和治理目录职责
            ),
            "progressive_disclosure_policy": "Keep SKILL.md concise, move detailed policy into references/, and let scripts own deterministic governance work.",  # synthesized 用于本步治理判断
            "validation_gates": str_validation_gates,  # takeover skill 验证命令链
            "forward_testing_policy": "Forward-test takeover and governance repair flows with fresh fixtures before claiming readiness.",  # synthesized 用于本步治理判断
            "development_requirements": (  # takeover skill 治理要求
                "Force-take over the existing skill workspace, normalize structure, "  # skill 接管结构整理要求
                "rebuild governance docs, and restore version-aligned AGENTS control."  # skill 接管文档治理要求
            ),
            "expected_outcome": (  # takeover skill 完成状态
                "The existing skill workspace is reorganized under the governed structure "  # skill 接管后的目录状态
                "and can be maintained through the standard agents-md-generator workflow."  # skill 接管后的维护状态
            ),
            "validation_method": "automated scripts plus user review",  # synthesized 用于本步治理判断
            "validation_granularity": "unit tests, AGENTS verification, docs governance verification, and evaluate chain",  # synthesized 用于本步治理判断
        }
    else:

        # 保留 synthesized 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
        dict_synthesized = {  # synthesized 用于本步治理判断
            "development_type": "engineering",  # synthesized 用于本步治理判断
            "name": name_value,  # synthesized 用于本步治理判断
            "project_purpose": f"Take over and govern the existing `{name_value}` engineering workspace.",  # synthesized 用于本步治理判断
            "project_reason": "Root AGENTS.md is missing or outdated, so the engineering workspace must be reorganized and brought under strict governance.",  # synthesized 用于本步治理判断
            "reusable_experience": "This control profile was generated by takeover mode from repository facts and minimal user confirmation.",  # synthesized 用于本步治理判断
            "development_requirements": (  # takeover engineering 治理要求
                "Force-take over the existing engineering workspace, normalize the local "  # 工程接管结构整理要求
                "directory structure, and rebuild governance records without a full design interview."  # 工程接管文档治理要求
            ),
            "expected_outcome": (  # takeover engineering 完成状态
                "The engineering workspace is reorganized under the governed project root "  # 工程接管后的目录状态
                "and all AGENTS/docs governance gates become enforceable."  # 工程接管后的治理状态
            ),
            "environment": "local",  # synthesized 用于本步治理判断
            "resource_plan": (  # takeover engineering 目录职责说明
                f"{local_primary} for source and project files, tests/ for verification, "  # 工程源码和测试目录职责
                "dist/ for release artifacts, docs/ for governance, and .agents/ for control state."  # 工程发布和治理目录职责
            ),
            "validation_method": "automated scripts plus user review",  # synthesized 用于本步治理判断
            "validation_granularity": "unit tests, AGENTS verification, docs governance verification, and evaluate chain",  # synthesized 用于本步治理判断
            "forward_testing_policy": "Forward-test takeover restructuring and governance repair with fresh engineering fixtures before claiming readiness.",  # synthesized 用于本步治理判断
            "engineering_rule_primary": "none",  # synthesized 用于本步治理判断
            "engineering_rule_mode": "none",  # synthesized 用于本步治理判断
            "engineering_rule_scope": "on-demand",  # synthesized 用于本步治理判断
            "engineering_rule_notes": "",  # synthesized 用于本步治理判断
        }

    # 调用 update 完成 autogenerated_takeover_answers 的当前动作。
    dict_synthesized.update(
        {
            "git_management": "yes-local-only",
            "branch_model": "master-and-dist-release",
            "release_contract": f"dist/{name_value}-vx.x.x plus zip",
            "has_existing_work": "yes",
            "takeover_mode": True,
            ALIGNMENT_KEY: True,
            "reference_materials": dict_answers.get("reference_materials", ["none"]) if kind == "skill" else dict_answers.get("reference_materials", []),
        }
    )

    # 调用 update 完成 autogenerated_takeover_answers 的当前动作。
    dict_synthesized.update(dict_answers)

    # 检查 autogenerated_takeover_answers 的当前条件是否需要进入专门分支。
    if default_language:

        # 保留 中间载荷 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
        dict_synthesized["default_conversation_language"] = default_language  # 中间载荷 用于本步治理判断

    # 保留 中间载荷 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
    dict_synthesized[ALIGNMENT_KEY] = True  # 中间载荷 用于本步治理判断

    # 保留 policy 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
    policy = git_branch_policy()  # policy 用于本步治理判断

    # 保留 local primary 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
    local_primary = str(dict_synthesized.get("local_directory_structure", local_primary)).split(",")[0].strip().rstrip("/")  # local primary 用于本步治理判断

    # 保留 中间载荷 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
    policy["release_prepare_allowed_paths"] = [local_primary, "tests", "docs", ".agents", "AGENTS.md", "dist"]  # 中间载荷 用于本步治理判断

    # 保留 中间载荷 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
    dict_synthesized["git_branch_policy"] = policy  # 中间载荷 用于本步治理判断

    # 收集 takeover reasons 条目，保持 autogenerated_takeover_answers 的处理顺序稳定。
    list_takeover_reasons = list(state.get("takeover_trigger_reasons", []))  # takeover reasons 用于本步治理判断

    # 检查 autogenerated_takeover_answers 的当前条件是否需要进入专门分支。
    if kind == "skill":

        # 保留 中间载荷 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
        str_reason_text = ", ".join(list_takeover_reasons) or "workspace takeover required"  # takeover 触发原因文本

        # skill takeover 说明需要记录触发原因，便于后续审计接管来源。
        dict_synthesized["design_notes"] = (  # takeover skill 设计说明补充
            f"{dict_synthesized['design_notes']} Takeover reasons: {str_reason_text}."  # skill 接管触发原因补充文本
        )
    else:

        # 保留 中间载荷 中间值，支撑 autogenerated_takeover_answers 的当前计算步骤。
        str_reason_text = ", ".join(list_takeover_reasons) or "workspace takeover required"  # takeover 触发原因文本

        # engineering takeover 说明需要记录触发原因，便于后续审计接管来源。
        dict_synthesized["reusable_experience"] = (  # takeover engineering 经验说明补充
            f"{dict_synthesized['reusable_experience']} Takeover reasons: {str_reason_text}."  # 工程接管触发原因补充文本
        )

    # 返回 autogenerated_takeover_answers 已整理完成的调用载荷。
    return dict_synthesized


# 定义 complete_takeover 的脚本治理处理入口。
def complete_takeover(project: Path, state: dict[str, Any], move_to_extra_requirements) -> dict[str, Any]:

    # 收集 final answers 条目，保持 complete_takeover 的处理顺序稳定。
    """说明 complete_takeover 在 AGENTS 治理流程中的状态处理职责。
    
    数组契约:
        shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
        dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
        unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 明确该赋值在接管流程流程中的业务用途。
    dict_final_answers = autogenerated_takeover_answers(project, state)  # final answers 用于本步治理判断

    # 调用 pop 完成 complete_takeover 的当前动作。
    dict_final_answers.pop(ALIGNMENT_KEY, None)

    # 调用 pop 完成 complete_takeover 的当前动作。
    dict_final_answers.pop(DESIGN_REVIEW_KEY, None)

    # 保留 中间载荷 中间值，支撑 complete_takeover 的当前计算步骤。
    state["answers"] = dict_final_answers  # 中间载荷 用于本步治理判断

    # 调用 pop 完成 complete_takeover 的当前动作。
    state.pop("profile_preview", None)

    # 返回 complete_takeover 已整理完成的调用载荷。
    return move_to_extra_requirements(project, state)


