# 补充设计访谈状态代码段的职责说明。
"""维护 AGENTS.md 设计访谈流程的持久化状态和状态机跳转。"""

# 导入 设计访谈状态 所需的依赖模块。
from __future__ import annotations

# JSON 持久化与路径类型支持状态文件读写。
import json
from pathlib import Path
from typing import Any

# 导入 设计访谈状态 所需的依赖模块。
from agents_common import emit_json

# 知识图谱依赖合同负责本地安装发现和人工安装指引。
from codebase_memory_mcp import detect_codebase_memory_mcp, installation_guidance

# 画像构建模块提供访谈完成后的结构化设计合同。
from design_profile_builder import (
    attach_alignment,
    build_profile,
    infer_kind,
    review_summary,
    takeover_required,
)

# 分隔当前密集代码块，保留原有执行顺序。
from design_questions import (
    ALIGNMENT_KEY,
    COMMON_GROUPS,
    COMMON_QUESTIONS,
    CODEBASE_MEMORY_INSTALL_CONFIRM_KEY,
    DESIGN_REVIEW_KEY,
    EXTRA_REQUIREMENTS_KEY,

    # 再次分隔当前长代码块，降低连续语句密度。
    GROUP_CONFIRMATION_KEY,
    OPTIONAL_EMPTY_KEYS,
    REMOTE_CONFIGURATION_MODE_KEY,
    REMOTE_DIRECTORY_POLICY_KEYS,
    remote_directory_policy_required,
    REMOTE_INSTALL_CONFIRM_KEY,
    REMOTE_SERVER_TASK_ROUTES_KEY,

    # 分隔导入清单的后续成员，避免超长连续导入块。
    REMOTE_SSH_GIT_URL,
    REMOTE_SSH_INSTALL_SPECS,
    REMOTE_SSH_SKILL_NAME,
    REMOTE_VALIDATION_STATUS_KEY,
    REVIEW_REWORK_CONFIRMATION_KEY,

    # 分隔导入清单末段，保证分组阅读边界清楚。
    STATE_PATH,
    TAKEOVER_COMMON_GROUPS,
    TERMINAL_STATUSES,
    USE_REMOTE_SERVER_KEY,
    USE_CODEBASE_MEMORY_MCP_KEY,
    empty,

    # 分隔最后一组导入成员，避免阅读时连续清单过长。
    groups_for,
    now_iso,
    question_ids_to_keys,
    question_rows,
    questions_for,

    # 分隔状态机导入清单尾段，避免单块导入过长。
    takeover_groups_for,
    with_options,
)
from design_remote_gate import (
    normalize_remote_server_registry,

    # 分隔远程门禁导入清单，保持状态机依赖分组清楚。
    normalize_remote_task_list,
    normalize_remote_task_routes,
    remote_choices,
    remote_configure_command_hint,
    remote_dependency_summary,
    remote_discover,

    # 分隔远程配置导入清单尾段，降低状态机依赖密度。
    remote_gate_payload,
    remote_install_command_hint,
    resolve_remote_server_for_task,
    server_registry_map,
    set_remote_gate_payload,
    use_remote_server_enabled,
    validate_route_server_ids,
)

# 接管和审查模块提供状态机后半段依赖。
from design_takeover import autogenerated_takeover_answers, complete_takeover
from design_review_gate import (
    answers_without_design_review,
    design_review_request,
    design_review_requires_rework,
    normalize_extra_requirements,

    # 分隔状态写入导入清单尾段，结束长依赖列表。
    validate_design_review,
)
from agents_decisions import decision_request

# 模块依赖准备：公开该职责的状态转换入口
def normalize_intent(value: Any) -> str:
    """把外部输入的执行意图收敛到状态机支持的两种模式。

    # 补充设计访谈状态代码段的职责说明。
    参数:
        value: CLI、JSON 状态或调用方传入的意图值。

    # 补充设计访谈状态代码段的职责说明。
    返回:
        ``read_only`` 或 ``write``；未知值按写入流程处理，保持历史默认行为。
    """

    # 先做字符串归一化，避免 None、空白和大小写差异污染状态文件。
    str_intent = str(value or "write").strip().lower()  # 访谈流程意图

    # 只读流程是唯一的特殊分支，其余输入都回落到写入流程。
    return "read_only" if str_intent == "read_only" else "write"

# 执行意图归一：公开该职责的状态转换入口
def review_policy_for_state(state: dict[str, Any], status: str | None = None) -> str:
    """根据当前状态判断是否需要子代理复核。

    # 补充设计访谈状态代码段的职责说明。
    参数:
        state: 设计访谈状态字典。
        status: 调用方临时指定的状态；为空时读取状态文件中的 ``status``。

    # 补充设计访谈状态代码段的职责说明。
    返回:
        复核策略标识，供交互 payload 和写入阶段判断审核边界。
    
        数组契约:
            shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
            dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
            unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 使用显式覆盖状态支持预览分支，不提前修改持久化状态。
    str_resolved_status = status or str(state.get("status", "collecting_group"))  # 当前状态名

    # 已完成的只读流程不能再要求写入式复核。
    if str_resolved_status == "completed_read_only":

        # 返回 review_policy_for_state 的访谈状态载荷。
        return "read_only_no_subagent_review"

    # 只有显式进入设计复核的状态才要求子智能体审查。
    if str_resolved_status in {"awaiting_design_review", "awaiting_review_rework"}:

        # 审查策略选择：为用户显式请求的复核状态选择子智能体审查。
        return "subagent_review_required"

    # 已完成写入仅在携带本轮设计审查证据时标记为显式审查流程。
    if str_resolved_status == "completed" and DESIGN_REVIEW_KEY in state.get("answers", {}):

        # 审查策略选择：保留用户显式请求审查的完成证据。
        return "user_requested_subagent_review"

    # 默认完成态不因任务复杂度或写入意图自动要求审查智能体。
    if str_resolved_status == "completed":

        # 审查策略选择：写入已完成且未请求子智能体审查。
        return "write_no_subagent_review"

    # 只读意图在未进入写入复核前始终走轻量确认策略。
    if normalize_intent(state.get("intent")) == "read_only":

        # 审查策略选择：让只读状态跳过子代理审查
        return "read_only_no_subagent_review"

    # 访谈中的写入流程尚未具备最终复核对象。
    return "design_interview_in_progress"

# 审查策略选择：公开该职责的状态转换入口
def state_path(project: Path) -> Path:
    """返回设计访谈状态文件在项目内的固定位置。

    参数:
        project: 项目根目录。

    返回:
        项目根下的状态文件路径。

    异常:
        RuntimeError: 项目根为符号链接或状态路径越界、含符号链接时抛出。
    """

    # 项目根和状态路径必须保持在同一真实目录树内。
    path_project_absolute = project.absolute()  # 当前项目的绝对路径锚点。

    # 解析项目根，供后续路径边界比较使用。
    path_project_resolved = path_project_absolute.resolve()  # 当前项目的真实路径锚点。

    # 项目根本身若是符号链接，无法证明后续写入目标仍属于当前项目。
    if path_project_absolute != path_project_resolved:

        # 符号链接项目根不能作为状态写入的可信边界。
        raise RuntimeError("> ERR: [Python] interview state project root must not be a symbolic link")

    # 状态文件路径由共享常量控制，避免 CLI 和恢复流程写入不同位置。
    path_state = path_project_absolute / STATE_PATH  # 项目内的访谈状态文件路径。

    # 解析后的目标必须落在项目根下，拒绝常量或目录结构越界。
    try:

        # 通过真实路径相对关系验证状态文件没有越出项目根。
        path_state.resolve(strict=False).relative_to(path_project_resolved)

    # 越界路径必须转换为带治理前缀的明确错误。
    except ValueError as error:

        # 记录状态路径越界，阻止后续任何写入动作。
        raise RuntimeError("> ERR: [Python] interview state path escapes project root") from error

    # 已存在的每一级目录都不能通过符号链接跳出项目边界。
    path_cursor = path_project_resolved  # 逐级检查时使用的真实路径游标。

    # 逐级检查状态路径的既有目录组件。
    for str_part in path_state.relative_to(path_project_absolute).parts:

        # 把当前相对组件加入真实路径游标。
        path_cursor /= str_part  # 将当前路径组件并入边界检查游标。

        # 发现符号链接组件时立即阻断状态写入。
        if path_cursor.is_symlink():

            # 公开具体组件名称，便于定位不可信边界。
            raise RuntimeError(
                f"> ERR: [Python] interview state path contains symbolic component: {str_part}"
            )

    # 返回经过项目根和符号链接检查的状态文件路径。
    return path_state

# 状态路径定位：公开该职责的状态转换入口
def read_state(project: Path) -> dict[str, Any] | None:
    """读取项目中的设计访谈状态。

    # 补充设计访谈状态代码段的职责说明。
    参数:
        project: 工作区根目录。

    # 补充设计访谈状态代码段的职责说明。
    返回:
        合法的状态字典；文件缺失、JSON 损坏或根类型不正确时返回 ``None``。
    """

    # 统一定位状态文件，保证读取路径与写入路径完全一致。
    path_state = state_path(project)  # 设计访谈状态文件

    # 没有状态文件表示当前没有可恢复访谈。
    if not path_state.exists():

        # JSON 根节点不是对象时视为损坏状态，不向下游泄露异常结构。
        return None

    # 状态读取失败时保持恢复流程可继续启动新访谈。
    try:

        # 保存 state data 映射，维持 read_state 的字段关系。
        dict_state_data = json.loads(path_state.read_text(encoding="utf-8"))  # 反序列化后的状态内容

    # JSON 解析或文件读取失败时按无可恢复状态处理。
    except Exception:

        # 状态文件读取：在缺少有效结果时显式结束当前路径
        return None

    # 仅接受对象根节点，防止数组或标量 JSON 被误当成状态。
    return dict_state_data if isinstance(dict_state_data, dict) else None

# 状态文件读取：公开该职责的状态转换入口
def write_state(project: Path, state: dict[str, Any]) -> Path:
    """把访谈状态写回项目，并刷新更新时间。

    # 补充设计访谈状态代码段的职责说明。
    参数:
        project: 工作区根目录。
        state: 将被持久化的状态字典；调用方持有的同一对象会同步获得 ``updated_at``。

    # 补充设计访谈状态代码段的职责说明。
    返回:
        实际写入的状态文件路径。
    
        数组契约:
            shape/维度: 本函数处理 AGENTS 状态、JSON 记录或文件路径，不接收数值数组，数组维度不适用。
            dtype/类型: 输入输出由 dict、list、str、Path 等 Python 业务类型约束，非 ndarray dtype。
            unit/单位: 无物理量单位，字段含义以 AGENTS 治理配置和状态文件 schema 为准。
    """

    # 状态目录可能在首次访谈时尚未创建。
    path_state = state_path(project)  # 状态快照写入：保存当前分支产生的数据。

    # 创建父目录只影响治理状态目录，不改变项目源码结构。
    path_state.parent.mkdir(exist_ok=True)

    # mkdir 后重新确认目录未被替换，避免把状态写入外部链接目标。
    path_state = state_path(project)  # mkdir 后重新确认的状态文件路径。

    # 每次持久化都刷新时间戳，用于恢复流程识别最新进度。
    state["updated_at"] = now_iso()  # 访谈状态值

    # 排序写入让状态 diff 稳定，便于 handoff 和恢复排查。
    path_state.write_text(json.dumps(state, indent=2, sort_keys=True), encoding="utf-8")

    # 返回路径方便 CLI 输出或测试断言。
    return path_state

# 状态快照写入：公开该职责的状态转换入口
def is_active_state(state: dict[str, Any] | None) -> bool:
    """判断状态是否仍处于可继续的访谈流程。

    参数：state 为可空的访谈状态字典。
    返回：状态存在且尚未进入终态时为真。
    数组契约：shape、dtype 与 unit 均不适用，本函数处理 JSON 状态映射。
    """

    # 空状态和终态都不应阻塞新的访谈或只读检查。
    return bool(state) and str(state.get("status", "")) not in TERMINAL_STATUSES

# 活动状态识别：公开该职责的状态转换入口
def initial_state(project: Path, intent: str = "write") -> dict[str, Any]:
    """构造普通交互式设计访谈的初始状态。

    参数：project 为项目根目录；intent 为写入或只读意图。
    返回：可直接持久化的普通访谈初始状态。
    """

    # 初始状态字段保持稳定 JSON 结构，历史恢复和测试依赖这些 key。
    return {
        "schema_version": 1,  # 状态文件结构版本
        "mode": "interactive",  # 普通访谈模式
        "intent": normalize_intent(intent),  # 归一化后的执行意图
        "status": "collecting_group",  # 首个问题组收集阶段
        "project": str(project),  # 当前工作区路径快照
        "inferred_kind": infer_kind(project),  # 从项目事实推断出的类型
        "kind": None,  # 用户最终确认的项目类型
        "groups": COMMON_GROUPS,  # 普通访谈问题组
        "current_group_index": 0,  # 当前问题组索引
        "answers": {},  # 已收集回答
        "confirmed_group_indices": [],  # 已确认的问题组索引
        "started_at": now_iso(),  # 访谈开始时间
        "updated_at": now_iso(),  # 最近持久化时间
    }

# 普通访谈初始化：公开该职责的状态转换入口
def initial_takeover_state(project: Path, intent: str = "write") -> dict[str, Any]:
    """构造接管异常工作区时的访谈初始状态。

    # 补充设计访谈状态代码段的职责说明。
    参数:
        project: 工作区根目录。
        intent: 写入或只读意图。

    # 补充设计访谈状态代码段的职责说明。
    返回:
        包含接管触发证据快照的状态字典。

    # 补充设计访谈状态代码段的职责说明。
    异常:
        ValueError: 当前工作区不满足接管模式的前置条件。
    """

    # 接管模式只允许用于已有内容且根 AGENTS 异常的工作区。
    bool_required, dict_facts = takeover_required(project)  # 接管前置判断和证据

    # 非接管场景必须由普通访谈入口处理，避免错误写入 takeover 证据。
    if not bool_required:

        # 异常接管初始化：拒绝继续处理已经确认的非法状态
        raise ValueError("> ERR: [Python] takeover mode requires a landed workspace with abnormal root AGENTS.md state")

    # 证据快照写入状态文件，确保后续提示不依赖临时扫描结果。
    return {
        "schema_version": 1,  # 异常接管初始化：声明接管状态采用的协议版本
        "mode": "takeover",  # 接管访谈模式
        "intent": normalize_intent(intent),  # 异常接管初始化：记录规范化后的执行意图
        "status": "collecting_group",  # 首个接管问题组收集阶段
        "project": str(project),  # 异常接管初始化：固化本次访谈对应的工作区位置
        "inferred_kind": infer_kind(project),  # 异常接管初始化：保留依据项目事实推断的工程类型
        "kind": None,  # 异常接管初始化：预留等待用户确认的项目类型
        "groups": TAKEOVER_COMMON_GROUPS,  # 接管模式问题组
        "current_group_index": 0,  # 异常接管初始化：标记当前正在收集的问题组序号
        "answers": {},  # 异常接管初始化：承载跨轮次累积的用户回答
        "confirmed_group_indices": [],  # 异常接管初始化：累计已经人工确认的问题组序号
        "started_at": now_iso(),  # 异常接管初始化：记录访谈首次启动时间
        "updated_at": now_iso(),  # 异常接管初始化：记录状态最近一次持久化时间
        "takeover_trigger_reasons": list(dict_facts.get("root_agents_md_trigger_reasons", [])),  # 根 AGENTS 异常原因
        "facts_snapshot": {
            "root_agents_md_exists": dict_facts.get("root_agents_md_exists", False),
            "root_agents_md_trigger_reasons": dict_facts.get("root_agents_md_trigger_reasons", []),
            "structure_fix_reasons": dict_facts.get("structure_fix_reasons", []),
            "session_history_bootstrap_required": dict_facts.get("session_history_bootstrap_required", False),
        },
    }

# 异常接管初始化：公开该职责的状态转换入口
def move_to_extra_requirements(project: Path, state: dict[str, Any]) -> dict[str, Any]:
    """把访谈推进到额外需求收集阶段并返回交互 payload。

    参数：project 为项目根目录；state 为将被原位推进的访谈状态。
    返回：附加需求阶段的交互载荷。
    数组契约：shape 由状态字段决定，dtype 为 JSON 映射，unit 不适用。
    """

    # 额外需求阶段需要清除旧复核回答，避免用户回退后沿用过期审核结论。
    state["status"] = "awaiting_extra_requirements"  # 附加需求迁移：把流程切换到附加需求收集阶段

    # 复核回答只对最终对齐后的内容有效。
    state.setdefault("answers", {}).pop(DESIGN_REVIEW_KEY, None)

    # 推进状态后立即持久化，保证中断恢复能停在正确阶段。
    write_state(project, state)

    # 返回下一步交互描述给 CLI 或调用方。
    return interactive_payload(project, state)

# 附加需求迁移：公开该职责的状态转换入口
def advance_after_remote_gate(project: Path, state: dict[str, Any]) -> dict[str, Any]:
    """远程门禁完成后推进访谈到下一个问题组或收尾阶段。

    参数：project 为项目根目录；state 为远程门禁完成后的状态。
    返回：下一问题组、附加需求或接管收尾阶段的交互载荷。
    数组契约：shape 由问题组数量决定，dtype 为 JSON 映射，unit 不适用。
    """

    # 当前问题组索引用于判断是否已经完成全部访谈组。
    int_index = int(state.get("current_group_index", 0))  # 远程门禁后续推进：标记当前正在收集的问题组序号

    # 接管模式在最后一组后交给接管收尾逻辑生成下一步状态。
    if str(state.get("mode", "interactive")) == "takeover" and int_index + 1 >= len(state.get("groups", [])):

        # 远程门禁后续推进：问题组完成后进入接管收尾流程
        return complete_takeover(project, state, move_to_extra_requirements)

    # 仍有后续问题组时，继续进入普通收集阶段。
    if int_index + 1 < len(state.get("groups", [])):

        # 整理 advance_after_remote_gate 需要的 中间载荷 访谈状态。
        state["current_group_index"] = int_index + 1  # 远程步骤结束后指向下一问题组

        # 远程门禁后续推进：建立后续状态判定所需的具体中间量
        state["status"] = "collecting_group"  # 远程门禁后续推进：推进到下一问题组的回答收集阶段

    # 没有后续问题组时进入附加需求收集。
    else:

        # 远程门禁后续推进：远程步骤结束后转入附加需求确认
        return move_to_extra_requirements(project, state)

    # 持久化推进后的索引，避免远程门禁重复触发。
    write_state(project, state)

    # 返回下一组问题的交互 payload。
    return interactive_payload(project, state)

# 知识图谱依赖就绪后恢复原有远程门禁与问题组推进顺序。
def advance_after_codebase_memory_gate(project: Path, state: dict[str, Any]) -> dict[str, Any]:
    """知识图谱依赖就绪后进入可选远程门禁或下一问题组。

    参数:
        project: 当前设计访谈项目根目录。
        state: 已通过知识图谱门禁的持久化访谈状态。

    返回:
        远程门禁或下一问题组对应的交互载荷。

    数组契约:
        shape 为 JSON 映射，dtype 为字符串键和 JSON 值，unit 不适用。
    """

    # 启用远程治理时必须先恢复远程服务器选择门禁。
    if use_remote_server_enabled(state.get("answers", {})):

        # 远程刷新结果存在时表示流程仍需用户操作。
        dict_remote_result = refresh_remote_gate(project, state)  # 可选远程交互载荷

        # 未完成远程门禁时直接返回对应交互问题。
        if dict_remote_result is not None:

            # 调用方应继续处理远程门禁，而不是提前进入下一问题组。
            return dict_remote_result

    # 未启用或已完成远程门禁时恢复普通访谈推进。
    return advance_after_remote_gate(project, state)

# 知识图谱刷新只读取本地依赖证据，不执行下载或配置写入。
def refresh_codebase_memory_gate(project: Path, state: dict[str, Any]) -> dict[str, Any] | None:
    """启用知识图谱时检测本地二进制与 Codex MCP 配置。

    参数:
        project: 当前设计访谈项目根目录。
        state: 包含知识图谱选择和门禁进度的访谈状态。

    返回:
        依赖未就绪时返回安装确认交互载荷；无需门禁或已就绪时返回 None。

    数组契约:
        shape 为 JSON 映射，dtype 为字符串键和 JSON 值，unit 不适用。
    """

    # 结构化回答决定知识图谱门禁是否适用于本轮访谈。
    dict_answers = state.get("answers", {})  # 当前访谈的设计回答

    # 未显式启用知识图谱时不得探测依赖或改变流程状态。
    if not isinstance(dict_answers, dict) or not dict_answers.get(USE_CODEBASE_MEMORY_MCP_KEY):

        # None 表示调用方可继续执行后续门禁。
        return None

    # 已有门禁状态可能包含用户之前确认安装的跨轮次证据。
    dict_gate = state.get("codebase_memory_gate", {})  # 持久化知识图谱门禁状态

    # 损坏的旧状态不能参与映射更新，需恢复为空门禁对象。
    if not isinstance(dict_gate, dict):

        # 新映射保留后续写入的稳定字段结构。
        dict_gate = {}  # 修复后的知识图谱门禁状态

    # 依赖探测同时验证二进制版本和 Codex MCP 配置。
    dict_dependency = detect_codebase_memory_mcp()  # 当前本地依赖证据

    # 本轮刷新覆盖易变依赖证据，但保留安装确认等跨轮次字段。
    dict_gate.update(
        {
            "enabled": True,
            "dependency": dict_dependency,
            "installation_guidance": installation_guidance(),
        }
    )

    # 门禁状态必须回写主状态，供交互载荷和后续轮次读取。
    state["codebase_memory_gate"] = dict_gate  # 最新知识图谱门禁状态

    # 二进制与 MCP 配置任一缺失都不能宣称知识图谱依赖就绪。
    if not dict_dependency["installed"] or not dict_dependency["configured"]:

        # 已确认安装时等待用户完成操作，否则先征求明确安装确认。
        state["status"] = (  # 下一轮知识图谱门禁状态
            "awaiting_codebase_memory_install_completion"  # 已确认后的完成检查
            if dict_gate.get("install_confirmed")  # 用户已确认自行安装
            else "awaiting_codebase_memory_install_confirmation"  # 首次安装确认
        )

        # 未就绪状态必须持久化，避免下一轮丢失确认进度。
        write_state(project, state)

        # 返回安装相关交互问题，阻止访谈越过依赖门禁。
        return interactive_payload(project, state)

    # 完整依赖证据允许后续写入路径继续执行。
    dict_gate["dependency_status"] = "ready"  # 已验证依赖状态

    # 就绪证据持久化后，后续流程无需重复安装确认。
    write_state(project, state)

    # None 通知调用方继续远程门禁或下一问题组。
    return None

# 安装确认入口只记录用户选择，不自动运行任何第三方安装命令。
def answer_codebase_memory_install_confirmation(
    project: Path,
    state: dict[str, Any],
    payload: dict[str, Any],
) -> dict[str, Any]:
    """记录人工安装选择；本流程绝不自动下载或执行安装器。

    参数:
        project: 当前设计访谈项目根目录。
        state: 等待安装确认的持久化访谈状态。
        payload: 用户提交的启用选择或安装确认答案。

    返回:
        关闭功能后的后续载荷，或等待安装完成的交互载荷。

    异常:
        SystemExit: 确认字段缺失、类型错误或用户拒绝安装时抛出。

    数组契约:
        shape 为 JSON 映射，dtype 为字符串键和 JSON 值，unit 不适用。
    """

    # 用户显式关闭功能时清除门禁并恢复正常访谈流程。
    if not payload.get(USE_CODEBASE_MEMORY_MCP_KEY, True):

        # 回答状态保留用户关闭知识图谱的明确选择。
        state.setdefault("answers", {})[USE_CODEBASE_MEMORY_MCP_KEY] = False  # 知识图谱禁用选择

        # 旧门禁证据不再适用于关闭后的流程。
        state.pop("codebase_memory_gate", None)

        # 关闭功能后从知识图谱门禁之后继续原有状态机。
        return advance_after_codebase_memory_gate(project, state)

    # 安装确认必须是显式布尔值，禁止字符串真值造成误安装理解。
    raw_confirmation = payload.get(CODEBASE_MEMORY_INSTALL_CONFIRM_KEY)  # 原始安装确认答案

    # 缺失或非布尔值时返回同一问题及精确字段诊断。
    if not isinstance(raw_confirmation, bool):

        # 机器可读交互载荷承载字段类型错误。
        emit_json(
            interactive_payload(
                project,
                state,
                errors=[f"{CODEBASE_MEMORY_INSTALL_CONFIRM_KEY} must be provided as true or false"],
            )
        )

        # 无效答案不能推进状态机。
        raise SystemExit(1)

    # 用户拒绝安装时保持功能启用选择，但明确报告依赖阻断。
    if not raw_confirmation:

        # 错误载荷说明可行的两种解除阻断方式。
        emit_json(
            interactive_payload(
                project,
                state,
                errors=[
                    "codebase-memory-mcp remains blocked until it is installed and configured "
                    "or use_codebase_memory_mcp is changed to false"
                ],
            )
        )

        # 拒绝安装且未关闭功能时必须停在当前门禁。
        raise SystemExit(1)

    # 接受安装只记录确认，不下载、不执行安装器。
    dict_gate = state.setdefault("codebase_memory_gate", {})  # 待更新的知识图谱门禁状态

    # 确认标记让下一轮切换为安装完成检查。
    dict_gate["install_confirmed"] = True  # 跨轮次保留人工授权证据

    # 状态机等待用户在外部完成二进制和 MCP 配置。
    state["status"] = "awaiting_codebase_memory_install_completion"  # 安装完成等待状态

    # 确认选择持久化后才能安全返回下一轮交互载荷。
    write_state(project, state)

    # 交互载荷显示安装指南和当前依赖探测结果。
    return interactive_payload(project, state)

# 远程门禁后续推进：公开该职责的状态转换入口
def refresh_remote_gate(project: Path, state: dict[str, Any]) -> dict[str, Any] | None:
    """刷新远程服务器门禁状态，并在需要用户操作时返回交互 payload。

    参数：project 为项目根目录；state 为当前访谈状态。
    返回：需要用户操作时的交互载荷；未启用远程治理时返回 ``None``。
    数组契约：shape 随候选服务器数量变化，dtype 为 JSON 映射，unit 不适用。
    """

    # 远程门禁只在用户已启用远程服务器治理时生效。
    dict_answers = state.get("answers", {})  # 远程门禁刷新：承载跨轮次累积的用户回答

    # 非字典回答视为状态损坏，保持普通流程不触发远程依赖。
    if not isinstance(dict_answers, dict) or not use_remote_server_enabled(dict_answers):

        # 远程门禁刷新：在缺少有效结果时显式结束当前路径
        return None

    # 门禁 payload 保留发现、选择和用户确认结果，避免重复询问。
    dict_gate = remote_gate_payload(state)  # 远程门禁状态

    # 依赖摘要判断 erie-remote-ssh 是否可用于后续服务器发现。
    dict_dependency = remote_dependency_summary()  # 远程技能依赖状态

    # 先写入依赖状态，方便缺依赖分支向用户展示安装信息。
    dict_gate.update(
        {
            "enabled": True,
            "dependency_required": True,
            "dependency_status": "installed" if dict_dependency["installed"] else "missing",
            "dependency_url": dict_dependency["url"],
            "install_specs": dict_dependency["install_specs"],
            "skill_dir": dict_dependency["skill_dir"],
        }
    )

    # 状态文件中的远程门禁字段是后续恢复远程流程的唯一依据。
    set_remote_gate_payload(state, dict_gate)

    # 依赖缺失时暂停问题组推进，等待用户安装或确认跳过。
    if not dict_dependency["installed"]:

        # 远程门禁刷新：建立后续状态判定所需的具体中间量
        state["status"] = (  # 远程门禁刷新：保存当前分支产生的数据
            "awaiting_remote_install_completion"  # 已授权安装时等待安装完成证据
            if dict_gate.get("install_confirmed")  # 远程门禁刷新：确认用户已授权安装远程依赖
            else "awaiting_remote_install_confirmation"  # 未授权安装时继续请求用户确认
        )

        # 调用 write_state 处理 refresh_remote_gate。
        write_state(project, state)

        # 远程门禁刷新：返回与最新持久化状态一致的交互响应
        return interactive_payload(project, state)

    # 已安装依赖后读取可用 SSH 配置状态。
    path_skill_dir = Path(dict_dependency["skill_dir"])  # erie-remote-ssh 依赖所在目录

    # 服务器发现结果决定是否进入配置补全或路由映射阶段。
    dict_discover, list_discover_errors = remote_discover(path_skill_dir)  # 远程发现结果和错误

    # 记录发现结果，恢复流程可直接展示相同证据。
    dict_gate["discover"] = dict_discover  # 远程门禁刷新：缓存远程环境发现结果供恢复流程复用

    # 更新门禁字段后再处理错误，保证错误页面也带有最新发现信息。
    set_remote_gate_payload(state, dict_gate)

    # 发现命令失败时保留当前阶段并把错误返回给调用方。
    if list_discover_errors:

        # 远程门禁刷新：在响应前持久化本次状态迁移
        write_state(project, state)

        # 远程门禁刷新：把当前阻断原因返回交互调用方
        return interactive_payload(project, state, errors=list_discover_errors)

    # 未配置或没有启用 SSH 时，要求用户先完成远程配置。
    if dict_discover.get("status") in {"not_configured", "no_enabled_ssh"}:

        # 已选配置方式时等待配置证据，否则先要求用户选择方式。
        state["status"] = (  # 配置阶段的下一状态
            "awaiting_remote_configuration_completion"  # 已有配置方式时等待配置完成
            if dict_gate.get("configuration_mode") in {"guided", "manual"}  # 远程门禁刷新：记录用户选择的远程配置方式
            else "awaiting_remote_configuration_confirmation"  # 尚未选择方式时请求配置确认
        )

        # 将配置阶段状态落盘，确保恢复后仍停留在同一门禁。
        write_state(project, state)

        # 向交互层展示配置阶段的下一项操作。
        return interactive_payload(project, state)

    # 配置可用后读取可选服务器列表，供用户映射任务路由。
    dict_choices, list_choice_errors = remote_choices(path_skill_dir)  # 远程服务器候选

    # 候选列表写入状态，避免下一次请求重复执行发现命令。
    dict_gate["choices"] = dict_choices  # 远程门禁刷新：缓存可选服务器清单避免重复探测

    # 持久化选择候选，后续 payload 可直接渲染服务器选项。
    set_remote_gate_payload(state, dict_gate)

    # 候选读取失败时将错误返回给用户处理。
    if list_choice_errors:

        # 候选发现失败也写回门禁证据，便于下一轮诊断。
        write_state(project, state)

        # 将服务器候选解析错误连同当前状态反馈给用户。
        return interactive_payload(project, state, errors=list_choice_errors)

    # 没有可选服务器时回到配置确认阶段，避免写入空路由。
    if dict_choices.get("status") != "available" or not dict_choices.get("servers"):

        # 空候选无法建立路由，流程退回配置方式确认。
        state["status"] = "awaiting_remote_configuration_confirmation"  # 远程门禁刷新：要求用户选择远程配置方式

        # 保存空候选对应的回退状态，避免恢复时误入路由阶段。
        write_state(project, state)

        # 明确告知交互层当前没有可供选择的服务器。
        return interactive_payload(
            project,
            state,
            errors=["erie-remote-ssh choices did not return selectable servers"],
        )

    # 依赖、配置和候选都可用后，等待用户为任务类型选择服务器路由。
    state["status"] = "awaiting_remote_server_route_mapping"  # 远程门禁刷新：要求用户确认任务到服务器的路由

    # 保存路由映射等待状态。
    write_state(project, state)

    # 返回包含服务器选项的交互 payload。
    return interactive_payload(project, state)

# 远程门禁刷新：公开该职责的状态转换入口
def current_group_ids(state: dict[str, Any]) -> list[str]:
    """返回当前问题组中的问题 ID 列表。

    参数：state 为包含问题组与当前索引的访谈状态。
    返回：当前问题组内字符串化的问题标识。
    数组契约：shape 等于当前问题数，dtype 为字符串列表，unit 不适用。
    """

    # 状态中的 groups 可能来自旧文件，读取时需要先做类型保护。
    list_groups = state.get("groups", [])  # 状态内的问题组列表

    # 当前索引用于从问题组列表中取出正在处理的分组。
    int_index = int(state.get("current_group_index", 0))  # 当前问题组解析：标记当前正在收集的问题组序号

    # 越界或结构异常时返回空列表，让上层 payload 给出可恢复提示。
    if not isinstance(list_groups, list) or int_index < 0 or int_index >= len(list_groups):

        # 当前问题组解析：无可用分组时返回稳定的空列表
        return []

    # 当前分组必须是列表；否则视为没有可展示问题。
    list_group = list_groups[int_index]  # 当前问题组

    # 问题 ID 统一转成字符串，避免 JSON 数字被下游直接拼接。
    return [str(item) for item in list_group] if isinstance(list_group, list) else []

# 当前问题组解析：公开该职责的状态转换入口
def confirmed_keys_for_state(state: dict[str, Any], include_current: bool = False) -> list[str]:
    """收集已经确认的问题组对应的回答 key。

    参数：state 为访谈状态；include_current 指示是否纳入当前待确认组。
    返回：按问题组顺序展开的已确认回答键。
    数组契约：shape 等于已确认问题数，dtype 为字符串列表，unit 不适用。
    """

    # 返回顺序跟随问题组顺序，保证摘要和测试输出稳定。
    list_keys: list[str] = []  # 已确认回答 key

    # groups 可能来自旧状态文件，后续循环只接受列表分组。
    list_groups = state.get("groups", [])  # 已确认字段汇总：读取持久化状态中的问题组序列

    # 确认索引来自 JSON，先转成整数集合便于快速判断。
    set_confirmed_indices = set(int(item) for item in state.get("confirmed_group_indices", []))  # 已确认索引

    # 部分确认页需要把当前组作为“待确认摘要”纳入已知 key。
    if include_current and state.get("status") in {
        "awaiting_group_confirmation",
        "awaiting_extra_requirements",
        "awaiting_final_alignment",
        "awaiting_design_review",
        "completed",
        "completed_read_only",
    }:

        # 已确认字段汇总：把当前问题组纳入已确认集合
        set_confirmed_indices.add(int(state.get("current_group_index", 0)))

    # 按原问题组顺序展开 key，避免 set 排序影响用户可读摘要。
    for int_index, list_group in enumerate(list_groups):

        # 校验 confirmed_keys_for_state 的访谈状态分支。
        if int_index in set_confirmed_indices and isinstance(list_group, list):

            # 已确认字段汇总：追加已确认问题组对应的回答键
            list_keys.extend(question_ids_to_keys([str(item) for item in list_group]))

    # 返回已经确认或按需包含当前组的回答 key。
    return list_keys

# 已确认字段汇总：公开该职责的状态转换入口
def remaining_groups_for_state(state: dict[str, Any]) -> list[list[str]]:
    """返回当前状态之后仍需要处理的问题组。

    参数：state 为包含问题组、索引和阶段的访谈状态。
    返回：从当前索引开始的问题组；收尾或终态返回空列表。
    数组契约：shape 由剩余组数和每组问题数决定，dtype 为嵌套字符串列表，unit 不适用。
    """

    # 原始问题组可能来自持久化 JSON，保留类型检查以防状态损坏。
    list_groups = state.get("groups", [])  # 剩余问题组计算：读取持久化状态中的问题组序列

    # 当前索引决定剩余问题组切片的起点。
    int_index = int(state.get("current_group_index", 0))  # 剩余问题组计算：标记当前正在收集的问题组序号

    # 进入收尾或完成阶段后，不再暴露剩余访谈问题。
    if state.get("status") in {
        "awaiting_extra_requirements",
        "awaiting_final_alignment",
        "awaiting_design_review",
        "awaiting_review_rework",
        "completed",
        "completed_read_only",
    }:

        # 剩余问题组计算：无可用分组时返回稳定的空列表
        return []

    # 仅在 groups 结构正常时返回字符串化问题 ID。
    return (
        [[str(item) for item in list_group] for list_group in list_groups[int_index:]]
        if isinstance(list_groups, list)
        else []
    )

# 剩余问题组计算：公开该职责的状态转换入口
def interactive_payload(
    project: Path,
    state: dict[str, Any],
    status_override: str | None = None,
    errors: list[str] | None = None,
) -> dict[str, Any]:
    """返回当前设计访谈状态对应的 CLI 交互 payload。

    参数：project 为项目根；state 为状态；status_override 为展示阶段；errors 为诊断列表。
    返回：由载荷构建器组装的机器可读交互字典。
    数组契约：shape 由交互选项数量决定，dtype 为 JSON 映射，unit 不适用。
    """

    # payload 组装分支较多，拆到内部模块以保持状态机入口文件尺寸可控。
    from design_interview_payload import build_interactive_payload

    # 保持原公开函数签名不变，调用方仍通过本模块访问状态机入口。
    return build_interactive_payload(project, state, status_override=status_override, errors=errors)

# 交互响应组装：公开该职责的状态转换入口
def update_groups_after_common_confirmation(state: dict[str, Any]) -> None:
    """依据用户确认的项目类型替换后续问题组。

    参数：state 为包含通用问题回答的状态，函数会原位更新类型和问题组。
    返回：无业务返回值。
    异常：development_type 非法时抛出 ValueError。
    数组契约：shape 由项目类型的问题组定义决定，dtype 为 JSON 映射，unit 不适用。
    """

    # 明确该赋值在设计访谈状态流程中的业务用途。
    str_kind = str(state.get("answers", {}).get("development_type", "")).strip()  # 项目类型确认：承载跨轮次累积的用户回答

    # 接管访谈使用异常仓库问题组，普通访谈使用标准问题组。
    if str_kind not in {"skill", "engineering"}:

        # 项目类型确认：拒绝继续处理已经确认的非法状态
        raise ValueError("> ERR: [Python] development_type must be skill or engineering after common confirmation")

    # 项目类型确认：建立后续状态判定所需的具体中间量
    state["kind"] = str_kind  # 项目类型确认：预留等待用户确认的项目类型

    # 项目类型确认：依据当前合同条件选择后续状态分支
    if str(state.get("mode", "interactive")) == "takeover":

        # 根据已确认类型装载接管模式专用问题组。
        state["groups"] = takeover_groups_for(str_kind)  # 项目类型确认：保存当前分支产生的数据

    # 普通访谈选择对应项目类型的标准问题组。
    else:

        # 标准模式按工程类型装载常规问题组。
        state["groups"] = groups_for(str_kind)  # 用户类型对应的普通问题组序列

# 项目类型确认：公开该职责的状态转换入口
def validate_group_answers(payload: dict[str, Any], expected_keys: list[str]) -> list[str]:
    """校验所有允许字段均为必填的问题组回答。

    参数：payload 为本轮回答；expected_keys 为允许且必填的字段。
    返回：字段缺失、额外或空值诊断列表。
    """

    # 问题组回答校验：向上层返回本职责计算完成的结果
    return validate_group_answers_with_optional(payload, expected_keys, expected_keys)

# 问题组回答校验：公开该职责的状态转换入口
def validate_group_answers_with_optional(
    payload: dict[str, Any],
    expected_keys: list[str],
    required_keys: list[str],
) -> list[str]:
    """校验允许字段与实际必填字段不同的问题组回答。

    参数：payload 为本轮回答；expected_keys 为允许字段；required_keys 为必填字段。
    返回：稳定排序并保留字段名的回答诊断列表。
    """

    # 收集 provided keys 访谈条目。
    set_provided_keys = set(payload)  # 可选回答校验：建立调用方实际提交字段的集合

    # 必填集合独立于允许集合，支持条件可选字段。
    set_expected = set(expected_keys)  # 可选回答校验：建立当前问题组允许字段的集合

    # 错误列表合并多类字段问题，调用方可一次完成修正。
    set_required = set(required_keys)  # 可选回答校验：建立不能为空的必填字段集合

    # 可选回答校验：建立后续状态判定所需的具体中间量
    list_errors: list[str] = []  # 可选回答校验：汇总本次回答校验发现的错误

    # 先识别合同之外的额外字段。
    list_extra = sorted(set_provided_keys - set_expected)  # 实际字段减去允许字段后的稳定排序结果

    # 再识别完全没有提交的必填字段。
    missing = sorted(set_required - set_provided_keys)  # 必填字段减去实际字段后的稳定排序结果

    # 可选回答校验：依据当前合同条件选择后续状态分支
    if list_extra:

        # 追加 validate_group_answers_with_optional 的访谈诊断。
        list_errors.append(f"out-of-group answers are not allowed for this step: {', '.join(list_extra)}")

    # 逐项检查 validate_group_answers_with_optional 访谈候选。
    for key in missing:

        # 可选回答校验：衔接下一项状态处理
        list_errors.append(f"missing required answer: {key}")

    # 可选回答校验：逐项核对当前集合中的状态成员
    for key in required_keys:

        # 显式提交的可空字段不参与空值诊断。
        if key in OPTIONAL_EMPTY_KEYS and key in payload:

            # 分隔 validate_group_answers_with_optional 的控制流边界。
            continue

        # 已提交但内容为空的必填字段仍属于缺失回答。
        if key in payload and empty(payload[key]):

            # 将具体字段名加入缺失回答诊断。
            list_errors.append(f"missing required answer: {key}")

    # 可选回答校验：向上层返回本职责计算完成的结果
    return list_errors

# 可选回答校验：公开该职责的状态转换入口
def answer_group(project: Path, state: dict[str, Any], payload: dict[str, Any]) -> dict[str, Any]:
    """校验并保存当前问题组回答。

    参数：project 为项目根；state 为访谈状态；payload 为当前问题组回答。
    返回：等待问题组确认的交互载荷。
    异常：回答合同不满足时输出诊断并抛出 SystemExit(1)。
    数组契约：shape 由当前问题数决定，dtype 为 JSON 映射，unit 不适用。
    """

    # 问题组回答提交：建立后续状态判定所需的具体中间量
    list_group_ids = current_group_ids(state)  # 问题组回答提交：取得当前问题组的问题标识列表

    # 问题标识先转换为载荷字段合同。
    list_expected_keys = question_ids_to_keys(list_group_ids)  # 当前问题组允许提交的回答键

    # 合并历史回答仅用于计算条件必填规则，尚不修改持久化状态。
    dict_merged_answers = dict(state.get("answers", {}))  # 问题组回答提交：承载跨轮次累积的用户回答

    # 问题组回答提交：把本轮回答合并进累计状态
    dict_merged_answers.update(payload)

    # 默认所有当前问题都必填，随后按远程策略收窄。
    list_required_keys = list(list_expected_keys)  # 问题组回答提交：把问题标识转换为允许提交的回答键

    # 问题组回答提交：依据当前合同条件选择后续状态分支
    if (
        any(key in list_expected_keys for key in REMOTE_DIRECTORY_POLICY_KEYS)
        and not remote_directory_policy_required(dict_merged_answers)
    ):

        # 未启用远程目录治理时排除相应条件字段。
        list_required_keys = [key for key in list_expected_keys if key not in REMOTE_DIRECTORY_POLICY_KEYS]  # 过滤后的实际必填键

    # 在写入状态前完整校验本轮回答载荷。
    list_errors = validate_group_answers_with_optional(  # 当前问题组的完整回答诊断
        payload,  # 本轮原始回答
        list_expected_keys,  # 当前组允许字段
        list_required_keys,  # 条件过滤后的必填字段
    )

    # 校验失败时保留原状态并返回全部错误。
    if list_errors:

        # 问题组回答提交：将校验错误输出到机器可读协议
        emit_json(interactive_payload(project, state, errors=list_errors))

        # 问题组回答提交：拒绝继续处理已经确认的非法状态
        raise SystemExit(1)

    # 问题组回答提交：为未启用的远程目录项填入禁用默认值
    dict_answers = state.setdefault("answers", {})  # 可原位合并本轮结果的累计回答字典

    # 校验通过后才把回答合并进持久化对象。
    dict_answers.update(payload)

    # 远程目录策略未启用时补齐四个兼容禁用值。
    if (
        any(key in list_expected_keys for key in REMOTE_DIRECTORY_POLICY_KEYS)
        and not remote_directory_policy_required(dict_answers)
    ):

        # Conda 环境目录不参与远程治理。
        dict_answers.setdefault("remote_conda_environment_layout", "disabled")

        # 活跃运行产物目录采用禁用占位值。
        dict_answers.setdefault("remote_run_artifact_active_layout", "disabled")

        # 备份运行产物目录同步保持关闭。
        dict_answers.setdefault("remote_run_artifact_backup_layout", "disabled")

        # 自动归档触发器在关闭策略下不可启用。
        dict_answers.setdefault("remote_run_archive_trigger", "disabled")

    # 提交完成后等待用户对整组回答进行确认。
    state["status"] = "awaiting_group_confirmation"  # 问题组回答提交：等待用户确认刚提交的问题组

    # 问题组回答提交：在响应前持久化本次状态迁移
    write_state(project, state)

    # 问题组回答提交：返回与最新持久化状态一致的交互响应
    return interactive_payload(project, state)

# 问题组回答提交：公开该职责的状态转换入口
def disable_remote_gate_and_continue(project: Path, state: dict[str, Any]) -> dict[str, Any]:
    """关闭远程门禁并继续后续访谈。

    参数：project 为项目根；state 为将被原位更新的访谈状态。
    返回：远程门禁之后的下一阶段交互载荷。
    数组契约：shape 由后续问题组决定，dtype 为 JSON 映射，unit 不适用。
    """

    # 远程流程关闭：为未启用的远程目录项填入禁用默认值
    state.setdefault("answers", {})[USE_REMOTE_SERVER_KEY] = False  # 远程流程关闭：承载跨轮次累积的用户回答

    # 远程流程关闭：移除关闭后不再有效的远程门禁载荷
    state.pop("remote_server_gate", None)

    # 远程流程关闭：向上层返回本职责计算完成的结果
    return advance_after_remote_gate(project, state)

# 远程流程关闭：公开该职责的状态转换入口
def answer_remote_install_confirmation(project: Path, state: dict[str, Any], payload: dict[str, Any]) -> dict[str, Any]:
    """处理远程依赖安装确认。

    参数：project 为项目根；state 为门禁状态；payload 为安装或禁用选择。
    返回：安装等待阶段或关闭远程后的交互载荷。
    异常：确认值缺失、非法或拒绝安装时输出诊断并抛出 SystemExit(1)。
    数组契约：shape 由门禁字段决定，dtype 为 JSON 映射，unit 不适用。
    """

    # 说明该控制语句在设计访谈状态流程中的分支职责。
    value_remote_enabled = payload.get(USE_REMOTE_SERVER_KEY)  # 用户提交的远程能力开关原值

    # 仅布尔 false 表示用户明确关闭远程能力。
    if isinstance(value_remote_enabled, bool) and not value_remote_enabled:

        # 远程安装确认：用户关闭远程能力后继续本地访谈
        return disable_remote_gate_and_continue(project, state)

    # 布尔确认决定继续安装门禁还是退出远程流程。
    if REMOTE_INSTALL_CONFIRM_KEY not in payload or not isinstance(payload[REMOTE_INSTALL_CONFIRM_KEY], bool):

        # 远程安装确认：将校验错误输出到机器可读协议
        emit_json(
            interactive_payload(
                project,
                state,
                errors=[f"{REMOTE_INSTALL_CONFIRM_KEY} must be provided as true or false"],
            )
        )

        # 远程安装确认：拒绝继续处理已经确认的非法状态
        raise SystemExit(1)

    # 远程安装确认：依据当前合同条件选择后续状态分支
    if payload[REMOTE_INSTALL_CONFIRM_KEY]:

        # 用户同意安装时更新门禁确认标志。
        dict_gate = remote_gate_payload(state)  # 远程安装确认：读取远程门禁的持久化载荷

        # 远程安装确认：建立后续状态判定所需的具体中间量
        dict_gate["install_confirmed"] = True  # 远程安装确认：确认用户已授权安装远程依赖

        # 将更新后的安装授权写回状态载荷。
        set_remote_gate_payload(state, dict_gate)

        # 安装授权完成后等待外部安装完成信号。
        state["status"] = "awaiting_remote_install_completion"  # 远程安装确认：等待远程依赖安装完成证据

        # 远程安装确认：在响应前持久化本次状态迁移
        write_state(project, state)

        # 远程安装确认：返回与最新持久化状态一致的交互响应
        return interactive_payload(project, state)

    # remote install 被取消时向调用方返回可恢复的阻断原因。
    list_errors = [  # 远程依赖缺失时返回给交互层的阻断原因
        "remote server flow remains blocked until erie-remote-ssh is installed "  # 远程依赖缺失说明
        "or use_remote_server is changed to false"  # 关闭远程流程的替代动作
    ]

    # 将阻断原因写入交互响应，保持状态文件不被误判为完成。
    emit_json(interactive_payload(project, state, errors=list_errors))

    # 用户拒绝安装但未关闭远程能力时保持阻断。
    raise SystemExit(1)

# 远程安装确认：公开该职责的状态转换入口
def answer_remote_configuration_confirmation(
    project: Path,
    state: dict[str, Any],
    payload: dict[str, Any],
) -> dict[str, Any]:
    """处理远程服务器配置方式确认。

    参数：project 为项目根；state 为门禁状态；payload 为配置模式或禁用选择。
    返回：配置等待阶段或关闭远程后的交互载荷。
    异常：配置模式非法或取消配置时输出诊断并抛出 SystemExit(1)。
    数组契约：shape 由配置字段决定，dtype 为 JSON 映射，unit 不适用。
    """

    # 显式关闭远程能力时立即返回本地访谈路径。
    value_remote_enabled = payload.get(USE_REMOTE_SERVER_KEY)  # 配置阶段收到的远程能力开关

    # 明确禁用时清理门禁，缺失值仍由配置合同处理。
    if isinstance(value_remote_enabled, bool) and not value_remote_enabled:

        # 远程配置确认：用户关闭远程能力后继续本地访谈
        return disable_remote_gate_and_continue(project, state)

    # 远程配置确认：建立后续状态判定所需的具体中间量
    str_mode = str(payload.get(REMOTE_CONFIGURATION_MODE_KEY, "")).strip().lower()  # 远程配置确认：记录用户选择的远程配置方式

    # cancel 仅取消本次配置，不等价于关闭远程能力。
    if str_mode not in {"guided", "manual", "cancel"}:

        # 远程配置确认：将校验错误输出到机器可读协议
        emit_json(
            interactive_payload(
                project,
                state,
                errors=[f"{REMOTE_CONFIGURATION_MODE_KEY} must be guided, manual, or cancel"],
            )
        )

        # 远程配置确认：拒绝继续处理已经确认的非法状态
        raise SystemExit(1)

    # 远程配置确认：依据当前合同条件选择后续状态分支
    if str_mode == "cancel":

        # 取消配置时构造可恢复的阻断说明。
        list_errors = [  # 远程配置未完成时返回给交互层的阻断原因
            "remote server flow remains blocked until configuration is completed "  # 远程配置缺失说明
            "or use_remote_server is changed to false"  # 远程配置确认：保存当前分支产生的数据
        ]

        # 通过交互协议展示继续配置或关闭远程能力两种选择。
        emit_json(interactive_payload(project, state, errors=list_errors))

        # 非零退出码阻止调用方把取消配置误判为完成。
        raise SystemExit(1)

    # 读取现有门禁载荷以保留发现和候选证据。
    dict_gate = remote_gate_payload(state)  # 远程配置确认：读取远程门禁的持久化载荷

    # 在原载荷中登记 guided 或 manual 选择。
    dict_gate["configuration_mode"] = str_mode  # 后续配置步骤采用的执行模式

    # 将配置模式与已有门禁证据一并写回主状态。
    set_remote_gate_payload(state, dict_gate)

    # 模式确认完成后等待实际配置完成证据。
    state["status"] = "awaiting_remote_configuration_completion"  # 远程配置确认：等待远程服务器配置完成证据

    # 远程配置确认：在响应前持久化本次状态迁移
    write_state(project, state)

    # 远程配置确认：返回与最新持久化状态一致的交互响应
    return interactive_payload(project, state)

# 服务器路由确认负责校验并持久化任务类型到服务器的映射。
